-- GoldAdvisorMidnight/Data/Professions/Alchemy.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Alchemy"] = {
  {
    id = "alchemy__composite_flora__midnight_1",
    name = "Composite Flora",
    patchTag = "midnight-1",
    recipeID = 1230855,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 4,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 4,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 6,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Composite Flora",
        itemIDs = { 241280, 241281 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__vicious_thalassian_flask_of_honor__midnight_1",
    name = "Vicious Thalassian Flask of Honor",
    patchTag = "midnight-1",
    recipeID = 1230883,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 2,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 6,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Vicious Thalassian Flask of Honor",
        itemIDs = { 241334, 241335 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__flask_of_the_blood_knights__midnight_1",
    name = "Flask of the Blood Knights",
    patchTag = "midnight-1",
    recipeID = 1230877,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 2,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 8,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Flask of the Blood Knights",
        itemIDs = { 241324, 241325 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__haranir_phial_of_perception__midnight_1",
    name = "Haranir Phial of Perception",
    patchTag = "midnight-1",
    recipeID = 1230873,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 4,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 6,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Haranir Phial of Perception",
        itemIDs = { 241316, 241317 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "alchemy__haranir_phial_of_finesse__midnight_1",
    name = "Haranir Phial of Finesse",
    patchTag = "midnight-1",
    recipeID = 1230870,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 4,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 3,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Haranir Phial of Finesse",
        itemIDs = { 241310, 241311 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "alchemy__flask_of_the_shattered_sun__midnight_1",
    name = "Flask of the Shattered Sun",
    patchTag = "midnight-1",
    recipeID = 1230878,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 2,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Flask of the Shattered Sun",
        itemIDs = { 241326, 241327 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__amani_extract__midnight_1",
    name = "Amani Extract",
    patchTag = "midnight-1",
    recipeID = 1230864,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Amani Extract",
        itemIDs = { 241298, 241299 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__potion_of_recklessness__midnight_1",
    name = "Potion of Recklessness",
    patchTag = "midnight-1",
    recipeID = 1230859,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Potion of Recklessness",
        itemIDs = { 241288, 241289 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__void_shrouded_tincture__midnight_1",
    name = "Void-Shrouded Tincture",
    patchTag = "midnight-1",
    recipeID = 1230867,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Void-Shrouded Tincture",
        itemIDs = { 241302, 241303 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__silvermoon_health_potion__midnight_1",
    name = "Silvermoon Health Potion",
    patchTag = "midnight-1",
    recipeID = 1230866,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Silvermoon Health Potion",
        itemIDs = { 241304, 241305 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__potion_of_zealotry__midnight_1",
    name = "Potion of Zealotry",
    patchTag = "midnight-1",
    recipeID = 1230863,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Potion of Zealotry",
        itemIDs = { 241296, 241297 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__lightfused_mana_potion__midnight_1",
    name = "Lightfused Mana Potion",
    patchTag = "midnight-1",
    recipeID = 1230865,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Lightfused Mana Potion",
        itemIDs = { 241300, 241301 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__draught_of_rampant_abandon__midnight_1",
    name = "Draught of Rampant Abandon",
    patchTag = "midnight-1",
    recipeID = 1230860,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 3,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Draught of Rampant Abandon",
        itemIDs = { 241292, 241293 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__light_s_potential__midnight_1",
    name = "Light's Potential",
    patchTag = "midnight-1",
    recipeID = 1230869,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 3,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Light's Potential",
        itemIDs = { 241308, 241309 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__flask_of_the_magisters__midnight_1",
    name = "Flask of the Magisters",
    patchTag = "midnight-1",
    recipeID = 1230876,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 6,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 2,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 2,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Flask of the Magisters",
        itemIDs = { 241323, 241322 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__refreshing_serum__midnight_1",
    name = "Refreshing Serum",
    patchTag = "midnight-1",
    recipeID = 1230868,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Refreshing Serum",
        itemIDs = { 241306, 241307 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__enlightenment_tonic__midnight_1",
    name = "Enlightenment Tonic",
    patchTag = "midnight-1",
    recipeID = 1230886,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Enlightenment Tonic",
        itemIDs = { 241338, 241339 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__entropic_extract__midnight_1",
    name = "Entropic Extract",
    patchTag = "midnight-1",
    recipeID = 1230854,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Entropic Extract",
        itemIDs = { 268955, 268954 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__potion_of_devoured_dreams__midnight_1",
    name = "Potion of Devoured Dreams",
    patchTag = "midnight-1",
    recipeID = 1230862,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 2,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 4,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Potion of Devoured Dreams",
        itemIDs = { 241294, 241295 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__lights_preservation__midnight_1",
    name = "Light's Preservation",
    patchTag = "midnight-1",
    recipeID = 1230858,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 2,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 4,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Light's Preservation",
        itemIDs = { 241286, 241287 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "alchemy__haranir_phial_of_ingenuity__midnight_1",
    name = "Haranir Phial of Ingenuity",
    patchTag = "midnight-1",
    recipeID = 1230872,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 2,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 8,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 6,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 3,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Haranir Phial of Ingenuity",
        itemIDs = { 241312, 241313 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "alchemy__flask_of_thalassian_resistance__midnight_1",
    name = "Flask of Thalassian Resistance",
    patchTag = "midnight-1",
    recipeID = 1230875,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 2,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 6,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 8,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Flask of Thalassian Resistance",
        itemIDs = { 241320, 241321 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "alchemy__voidlight_potion_cauldron__midnight_1",
    name = "Voidlight Potion Cauldron",
    patchTag = "midnight-1",
    recipeID = 1230857,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 20,
      },
      {
        itemRef = "Wondrous Synergist",
        itemIDs = { 241282, 241283 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Voidlight Potion Cauldron",
        itemIDs = { 241284, 241285 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "alchemy__cauldron_of_sindorei_flasks__midnight_1",
    name = "Cauldron of Sin'dorei Flasks",
    patchTag = "midnight-1",
    recipeID = 1230874,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Nocturnal Lotus",
        itemIDs = { 236780 },
        amount = 1,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 20,
      },
      {
        itemRef = "Wondrous Synergist",
        itemIDs = { 241282, 241283 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Cauldron of Sin'dorei Flasks",
        itemIDs = { 241318, 241319 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "alchemy__wondrous_synergist__midnight_1",
    name = "Wondrous Synergist",
    patchTag = "midnight-1",
    recipeID = 1230856,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 4,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 2,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 2,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 2,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 2,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Wondrous Synergist",
        itemIDs = { 241282, 241283 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "alchemy__transmute_mote_of_wild_magic__midnight_1",
    name = "Transmute: Mote of Wild Magic",
    patchTag = "midnight-1",
    recipeID = 1230887,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 10,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 2,
        skipDerivation = true,
      },
    },
    outputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        baseAmount = 8,
      },
    },
  },
  {
    id = "alchemy__transmute_mote_of_pure_void__midnight_1",
    name = "Transmute: Mote of Pure Void",
    patchTag = "midnight-1",
    recipeID = 1230888,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 10,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 2,
        skipDerivation = true,
      },
    },
    outputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        baseAmount = 8,
      },
    },
  },
  {
    id = "alchemy__transmute_mote_of_primal_energy__midnight_1",
    name = "Transmute: Mote of Primal Energy",
    patchTag = "midnight-1",
    recipeID = 1230889,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 10,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 2,
        skipDerivation = true,
      },
    },
    outputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        baseAmount = 8,
      },
    },
  },
  {
    id = "alchemy__transmute_mote_of_light__midnight_1",
    name = "Transmute: Mote of Light",
    patchTag = "midnight-1",
    recipeID = 1230890,
    formulaProfile = "alchemy",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 10,
      },
      {
        itemRef = "Stabilized Derivate",
        itemIDs = { 242651 },
        amount = 2,
        skipDerivation = true,
      },
    },
    outputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        baseAmount = 8,
      },
    },
  },
}
