-- GoldAdvisorMidnight/Data/Professions/Blacksmithing.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Blacksmithing"] = {
  {
    id = "blacksmithing__refulgent_copper_ingot__midnight_1",
    name = "Refulgent Copper Ingot",
    patchTag = "midnight-1",
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Refulgent Copper Ore",
        itemIDs = { 237359 },
        amount = 5,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        baseAmount = 1,
      },
    },
    rankVariants = {
      highest = {
        inputs = {
          {
            itemRef = "Refulgent Copper Ore",
            itemIDs = { 237359 },
            amount = 3,
          },
          {
            itemRef = "Refulgent Copper Ore",
            itemIDs = { 237361 },
            amount = 2,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 2,
          },
        },
        outputs = {
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238197, 238198 },
            baseAmount = 1,
          },
        },
      },
      lowest = {
        inputs = {
          {
            itemRef = "Refulgent Copper Ore",
            itemIDs = { 237359 },
            amount = 5,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 2,
          },
        },
        outputs = {
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238197, 238198 },
            baseAmount = 1,
          },
        },
      },
    },
  },
  {
    id = "blacksmithing__gloaming_alloy__midnight_1",
    name = "Gloaming Alloy",
    patchTag = "midnight-1",
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Umbral Tin Ore",
        itemIDs = { 237362 },
        amount = 6,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 4,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Gloaming Alloy",
        itemIDs = { 238202, 238203 },
        baseAmount = 1,
      },
    },
    rankVariants = {
      highest = {
        inputs = {
          {
            itemRef = "Umbral Tin Ore",
            itemIDs = { 237362 },
            amount = 3,
          },
          {
            itemRef = "Umbral Tin Ore",
            itemIDs = { 237363 },
            amount = 3,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 4,
          },
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238198 },
            amount = 3,
          },
        },
        outputs = {
          {
            itemRef = "Gloaming Alloy",
            itemIDs = { 238202, 238203 },
            baseAmount = 1,
          },
        },
      },
      lowest = {
        inputs = {
          {
            itemRef = "Umbral Tin Ore",
            itemIDs = { 237362 },
            amount = 6,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 4,
          },
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238197 },
            amount = 3,
          },
        },
        outputs = {
          {
            itemRef = "Gloaming Alloy",
            itemIDs = { 238202, 238203 },
            baseAmount = 1,
          },
        },
      },
    },
  },
  {
    id = "blacksmithing__sterling_alloy__midnight_1",
    name = "Sterling Alloy",
    patchTag = "midnight-1",
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Brilliant Silver Ore",
        itemIDs = { 237364 },
        amount = 6,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 4,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        baseAmount = 1,
      },
    },
    rankVariants = {
      highest = {
        inputs = {
          {
            itemRef = "Brilliant Silver Ore",
            itemIDs = { 237364 },
            amount = 3,
          },
          {
            itemRef = "Brilliant Silver Ore",
            itemIDs = { 237365 },
            amount = 3,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 4,
          },
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238198 },
            amount = 3,
          },
        },
        outputs = {
          {
            itemRef = "Sterling Alloy",
            itemIDs = { 238204, 238205 },
            baseAmount = 1,
          },
        },
      },
      lowest = {
        inputs = {
          {
            itemRef = "Brilliant Silver Ore",
            itemIDs = { 237364 },
            amount = 6,
          },
          {
            itemRef = "Luminant Flux",
            itemIDs = { 243060 },
            amount = 4,
          },
          {
            itemRef = "Refulgent Copper Ingot",
            itemIDs = { 238197 },
            amount = 3,
          },
        },
        outputs = {
          {
            itemRef = "Sterling Alloy",
            itemIDs = { 238204, 238205 },
            baseAmount = 1,
          },
        },
      },
    },
  },
  {
    id = "blacksmithing__thalassian_blacksmiths_hammer__midnight_1",
    name = "Thalassian Blacksmith's Hammer",
    patchTag = "midnight-1",
    recipeID = 1229606,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 3,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Blacksmith's Hammer",
        itemIDs = { 238013 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_leatherworkers_knife__midnight_1",
    name = "Thalassian Leatherworker's Knife",
    patchTag = "midnight-1",
    recipeID = 1229607,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 3,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Leatherworker's Knife",
        itemIDs = { 238012 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_skinning_knife__midnight_1",
    name = "Thalassian Skinning Knife",
    patchTag = "midnight-1",
    recipeID = 1229608,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 3,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Skinning Knife",
        itemIDs = { 238011 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_pickaxe__midnight_1",
    name = "Thalassian Pickaxe",
    patchTag = "midnight-1",
    recipeID = 1229609,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 3,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Pickaxe",
        itemIDs = { 238010 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_sickle__midnight_1",
    name = "Thalassian Sickle",
    patchTag = "midnight-1",
    recipeID = 1229610,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 3,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Sickle",
        itemIDs = { 238009 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_blacksmiths_toolbox__midnight_1",
    name = "Thalassian Blacksmith's Toolbox",
    patchTag = "midnight-1",
    recipeID = 1229611,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 4,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Blacksmith's Toolbox",
        itemIDs = { 237948 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_leatherworkers_toolset__midnight_1",
    name = "Thalassian Leatherworker's Toolset",
    patchTag = "midnight-1",
    recipeID = 1229612,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 4,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Leatherworker's Toolset",
        itemIDs = { 237947 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_needle_set__midnight_1",
    name = "Thalassian Needle Set",
    patchTag = "midnight-1",
    recipeID = 1229613,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 4,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Needle Set",
        itemIDs = { 237946 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_blacksmiths_hammer__midnight_1",
    name = "Sun-Blessed Blacksmith's Hammer",
    patchTag = "midnight-1",
    recipeID = 1229598,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Blacksmith's Hammer",
        itemIDs = { 238018 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_leatherworkers_knife__midnight_1",
    name = "Sun-Blessed Leatherworker's Knife",
    patchTag = "midnight-1",
    recipeID = 1229599,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Leatherworker's Knife",
        itemIDs = { 238017 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_skinning_knife__midnight_1",
    name = "Sun-Blessed Skinning Knife",
    patchTag = "midnight-1",
    recipeID = 1229600,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Skinning Knife",
        itemIDs = { 238016 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_pickaxe__midnight_1",
    name = "Sun-Blessed Pickaxe",
    patchTag = "midnight-1",
    recipeID = 1229601,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Pickaxe",
        itemIDs = { 238015 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_sickle__midnight_1",
    name = "Sun-Blessed Sickle",
    patchTag = "midnight-1",
    recipeID = 1229602,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Sickle",
        itemIDs = { 238014 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_blacksmiths_toolbox__midnight_1",
    name = "Sun-Blessed Blacksmith's Toolbox",
    patchTag = "midnight-1",
    recipeID = 1229603,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Fin",
        itemIDs = { 238530 },
        amount = 1,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 5,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Blacksmith's Toolbox",
        itemIDs = { 237952 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_leatherworkers_toolset__midnight_1",
    name = "Sun-Blessed Leatherworker's Toolset",
    patchTag = "midnight-1",
    recipeID = 1229604,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Hide",
        itemIDs = { 238529 },
        amount = 1,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 5,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Leatherworker's Toolset",
        itemIDs = { 237951 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__sun_blessed_needle_set__midnight_1",
    name = "Sun-Blessed Needle Set",
    patchTag = "midnight-1",
    recipeID = 1229605,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 5,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 2,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Blessed Needle Set",
        itemIDs = { 237950 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "blacksmithing__refulgent_whetstone__midnight_1",
    name = "Refulgent Whetstone",
    patchTag = "midnight-1",
    recipeID = 1230758,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 12,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Refulgent Whetstone",
        itemIDs = { 237370, 237371 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "blacksmithing__refulgent_weightstone__midnight_1",
    name = "Refulgent Weightstone",
    patchTag = "midnight-1",
    recipeID = 1230759,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 12,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Refulgent Weightstone",
        itemIDs = { 237367, 237369 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "blacksmithing__refulgent_razorstone__midnight_1",
    name = "Refulgent Razorstone",
    patchTag = "midnight-1",
    recipeID = 1230760,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 12,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Refulgent Razorstone",
        itemIDs = { 237372, 237373 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "blacksmithing__refulgent_repair_hammer__midnight_1",
    name = "Refulgent Repair Hammer",
    patchTag = "midnight-1",
    recipeID = 1230764,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 1,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 1,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Refulgent Repair Hammer",
        itemIDs = { 238209 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "blacksmithing__thalassian_skeleton_key__midnight_1",
    name = "Thalassian Skeleton Key",
    patchTag = "midnight-1",
    recipeID = 1265906,
    formulaProfile = "blacksmithing",
    inputs = {
      {
        itemRef = "Refulgent Copper Ore",
        itemIDs = { 237359, 237361 },
        amount = 6,
      },
      {
        itemRef = "Brilliant Silver Ore",
        itemIDs = { 237364, 237365 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Skeleton Key",
        itemIDs = { 260232 },
        baseAmount = 1,
      },
    },
  },
}
