-- GoldAdvisorMidnight/Data/Professions/Cooking.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Cooking"] = {
  {
    id = "cooking__champion_s_bento__midnight_1",
    name = "Champion's Bento",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 5,
      },
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 5,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 5,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Champion's Bento",
        itemIDs = { 242274 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__flora_frenzy__midnight_1",
    name = "Flora Frenzy",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 12,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 5,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flora Frenzy",
        itemIDs = { 255848 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__impossibly_royal_roast__midnight_1",
    name = "Impossibly Royal Roast",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 15,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 4,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 4,
      },
      {
        itemRef = "Ripened Vegetable Assortment",
        itemIDs = { 242645 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Impossibly Royal Roast",
        itemIDs = { 255847 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__royal_roast__midnight_1",
    name = "Royal Roast",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 15,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 4,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 4,
      },
      {
        itemRef = "Ripened Vegetable Assortment",
        itemIDs = { 242645 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Royal Roast",
        itemIDs = { 242275 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__blooming_feast__midnight_1",
    name = "Blooming Feast",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 10,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 5,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 5,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Blooming Feast",
        itemIDs = { 242273 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__harandar_celebration__midnight_1",
    name = "Harandar Celebration",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 10,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 4,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 3,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Harandar Celebration",
        itemIDs = { 255846 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__argentleaf_tea__midnight_1",
    name = "Argentleaf Tea",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Argentleaf Tea",
        itemIDs = { 242298 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__quel_dorei_medley__midnight_1",
    name = "Quel'dorei Medley",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Eversong Trout",
        itemIDs = { 238383 },
        amount = 6,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
      {
        itemRef = "Restored Songfish",
        itemIDs = { 238372 },
        amount = 4,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 10,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quel'dorei Medley",
        itemIDs = { 242272 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__silvermoon_parade__midnight_1",
    name = "Silvermoon Parade",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Lynxfish",
        itemIDs = { 238366 },
        amount = 4,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
      {
        itemRef = "Arcane Wyrmfish",
        itemIDs = { 238371 },
        amount = 4,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 10,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Silvermoon Parade",
        itemIDs = { 255845 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__azeroot_tea__midnight_1",
    name = "Azeroot Tea",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Azeroot Tea",
        itemIDs = { 242301 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__sanguithorn_tea__midnight_1",
    name = "Sanguithorn Tea",
    patchTag = "midnight-1",
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Sanguithorn Tea",
        itemIDs = { 242299 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__bloom_skewers__midnight_1",
    name = "Bloom Skewers",
    patchTag = "midnight-1",
    recipeID = 1226198,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bloom Skewers",
        itemIDs = { 242302 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__farstrider_rations__midnight_1",
    name = "Farstrider Rations",
    patchTag = "midnight-1",
    recipeID = 1226166,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 2,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 1,
      },
      {
        itemRef = "Thalassian Herbs",
        itemIDs = { 242642 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Farstrider Rations",
        itemIDs = { 242309 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__forager_s_medley__midnight_1",
    name = "Forager's Medley",
    patchTag = "midnight-1",
    recipeID = 1226202,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 2,
      },
      {
        itemRef = "Ripened Vegetable Assortment",
        itemIDs = { 242645 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Forager's Medley",
        itemIDs = { 242306 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__mana_infused_stew__midnight_1",
    name = "Mana-Infused Stew",
    patchTag = "midnight-1",
    recipeID = 1226199,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 1,
      },
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 1,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Mana-Infused Stew",
        itemIDs = { 242303 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__portable_snack__midnight_1",
    name = "Portable Snack",
    patchTag = "midnight-1",
    recipeID = 1226204,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 2,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 1,
      },
      {
        itemRef = "Thalassian Herbs",
        itemIDs = { 242642 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Portable Snack",
        itemIDs = { 242308 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__quick_sandwich__midnight_1",
    name = "Quick Sandwich",
    patchTag = "midnight-1",
    recipeID = 1226203,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 2,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quick Sandwich",
        itemIDs = { 242307 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__silvermoon_standard__midnight_1",
    name = "Silvermoon Standard",
    patchTag = "midnight-1",
    recipeID = 1226201,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 1,
      },
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 1,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Silvermoon Standard",
        itemIDs = { 242305 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__spiced_biscuits__midnight_1",
    name = "Spiced Biscuits",
    patchTag = "midnight-1",
    recipeID = 1226200,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Spiced Biscuits",
        itemIDs = { 242304 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__spellfire_filet__midnight_1",
    name = "Spellfire Filet",
    patchTag = "midnight-1",
    recipeID = 1226185,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 3,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Spellfire Filet",
        itemIDs = { 242289 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__twilight_angler_s_medley__midnight_1",
    name = "Twilight Angler's Medley",
    patchTag = "midnight-1",
    recipeID = 1226184,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 10,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Twilight Angler's Medley",
        itemIDs = { 242288 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__wise_tails__midnight_1",
    name = "Wise Tails",
    patchTag = "midnight-1",
    recipeID = 1226186,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Warping Wise",
        itemIDs = { 238379 },
        amount = 3,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
      {
        itemRef = "Thalassian Herbs",
        itemIDs = { 242642 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Wise Tails",
        itemIDs = { 242290 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__bloodthistle_wrapped_cutlets__midnight_1",
    name = "Bloodthistle-Wrapped Cutlets",
    patchTag = "midnight-1",
    recipeID = 1226192,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 10,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 2,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Bloodthistle-Wrapped Cutlets",
        itemIDs = { 242296 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__eversong_pudding__midnight_1",
    name = "Eversong Pudding",
    patchTag = "midnight-1",
    recipeID = 1226188,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Eversong Trout",
        itemIDs = { 238383 },
        amount = 1,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 5,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 2,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Eversong Pudding",
        itemIDs = { 242292 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__felberry_figs__midnight_1",
    name = "Felberry Figs",
    patchTag = "midnight-1",
    recipeID = 1226190,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 10,
      },
      {
        itemRef = "Ripened Vegetable Assortment",
        itemIDs = { 242645 },
        amount = 4,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Felberry Figs",
        itemIDs = { 242294 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__fried_bloomtail__midnight_1",
    name = "Fried Bloomtail",
    patchTag = "midnight-1",
    recipeID = 1226187,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Bloomtail Minnow",
        itemIDs = { 238369 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 10,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 5,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 5,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Fried Bloomtail",
        itemIDs = { 242291 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__hearthflame_supper__midnight_1",
    name = "Hearthflame Supper",
    patchTag = "midnight-1",
    recipeID = 1226191,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 7,
      },
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 7,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 2,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 4,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Hearthflame Supper",
        itemIDs = { 242295 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__sunwell_delight__midnight_1",
    name = "Sunwell Delight",
    patchTag = "midnight-1",
    recipeID = 1226189,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Sunwell Fish",
        itemIDs = { 238384 },
        amount = 4,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 12,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 5,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sunwell Delight",
        itemIDs = { 242293 },
        baseAmount = 4,
      },
    },
  },
  {
    id = "cooking__braised_blood_hunter__midnight_1",
    name = "Braised Blood Hunter",
    patchTag = "midnight-1",
    recipeID = 1226172,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Blood Hunter",
        itemIDs = { 238377 },
        amount = 6,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 3,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 3,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 3,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Braised Blood Hunter",
        itemIDs = { 242276 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__crimson_calamari__midnight_1",
    name = "Crimson Calamari",
    patchTag = "midnight-1",
    recipeID = 1226173,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Ominous Octopus",
        itemIDs = { 238373 },
        amount = 6,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 3,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 3,
      },
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Crimson Calamari",
        itemIDs = { 242277 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__tasty_smoked_tetra__midnight_1",
    name = "Tasty Smoked Tetra",
    patchTag = "midnight-1",
    recipeID = 1226174,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Twisted Tetra",
        itemIDs = { 238368 },
        amount = 6,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 4,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 4,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Tasty Smoked Tetra",
        itemIDs = { 242278 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__arcano_cutlets__midnight_1",
    name = "Arcano Cutlets",
    patchTag = "midnight-1",
    recipeID = 1226183,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Practically Pork",
        itemIDs = { 242639 },
        amount = 5,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Arcano Cutlets",
        itemIDs = { 242287 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__buttered_root_crab__midnight_1",
    name = "Buttered Root Crab",
    patchTag = "midnight-1",
    recipeID = 1226176,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Root Crab",
        itemIDs = { 238367 },
        amount = 6,
      },
      {
        itemRef = "Plant Protein",
        itemIDs = { 242640 },
        amount = 3,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 3,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 3,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Buttered Root Crab",
        itemIDs = { 242280 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__fel_kissed_filet__midnight_1",
    name = "Fel-Kissed Filet",
    patchTag = "midnight-1",
    recipeID = 1226182,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 5,
      },
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Cooking Spirits",
        itemIDs = { 242641 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Fel-Kissed Filet",
        itemIDs = { 242286 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__glitter_skewers__midnight_1",
    name = "Glitter Skewers",
    patchTag = "midnight-1",
    recipeID = 1226177,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Shimmersiren",
        itemIDs = { 238378 },
        amount = 2,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 5,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Glitter Skewers",
        itemIDs = { 242281 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__null_and_void_plate__midnight_1",
    name = "Null and Void Plate",
    patchTag = "midnight-1",
    recipeID = 1226178,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Warping Wise",
        itemIDs = { 238379 },
        amount = 2,
      },
      {
        itemRef = "Ominous Octopus",
        itemIDs = { 238373 },
        amount = 1,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 1,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Null and Void Plate",
        itemIDs = { 242282 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__sun_seared_lumifin__midnight_1",
    name = "Sun-Seared Lumifin",
    patchTag = "midnight-1",
    recipeID = 1226179,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Tender Lumifin",
        itemIDs = { 238374 },
        amount = 2,
      },
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 5,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sun-Seared Lumifin",
        itemIDs = { 242283 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__void_kissed_fish_rolls__midnight_1",
    name = "Void-Kissed Fish Rolls",
    patchTag = "midnight-1",
    recipeID = 1226180,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Thalassian Filet",
        itemIDs = { 253403 },
        amount = 4,
      },
      {
        itemRef = "Ripened Vegetable Assortment",
        itemIDs = { 242645 },
        amount = 2,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 1,
      },
      {
        itemRef = "Tavern Fixings",
        itemIDs = { 242647 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Void-Kissed Fish Rolls",
        itemIDs = { 242284 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__warped_wise_wings__midnight_1",
    name = "Warped Wise Wings",
    patchTag = "midnight-1",
    recipeID = 1226181,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Warping Wise",
        itemIDs = { 238379 },
        amount = 3,
      },
      {
        itemRef = "A Big Ol' Stick of Butter",
        itemIDs = { 242643 },
        amount = 3,
      },
      {
        itemRef = "Pouch of Spices",
        itemIDs = { 242646 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Warped Wise Wings",
        itemIDs = { 242285 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__mana_lily_tea__midnight_1",
    name = "Mana Lily Tea",
    patchTag = "midnight-1",
    recipeID = 1226193,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Mana Lily Tea",
        itemIDs = { 242297 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "cooking__tranquility_bloom_tea__midnight_1",
    name = "Tranquility Bloom Tea",
    patchTag = "midnight-1",
    recipeID = 1226196,
    formulaProfile = "cooking",
    inputs = {
      {
        itemRef = "Mana-Wyrm Essence",
        itemIDs = { 242644 },
        amount = 1,
      },
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Tranquility Bloom Tea",
        itemIDs = { 242300 },
        baseAmount = 2,
      },
    },
  },
}
