-- GoldAdvisorMidnight/Data/Professions/Enchanting.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Enchanting"] = {
  {
    id = "enchanting__oil_of_dawn__midnight_1",
    name = "Oil of Dawn",
    patchTag = "midnight-1",
    recipeID = 1236492,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Oil of Dawn",
        itemIDs = { 243735, 243736 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "enchanting__thalassian_phoenix_oil__midnight_1",
    name = "Thalassian Phoenix Oil",
    patchTag = "midnight-1",
    recipeID = 1236491,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Phoenix Oil",
        itemIDs = { 243733, 243734 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "enchanting__smuggler_s_enchanted_edge__midnight_1",
    name = "Smuggler's Enchanted Edge",
    patchTag = "midnight-1",
    recipeID = 1236493,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Smuggler's Enchanted Edge",
        itemIDs = { 243737, 243738 },
        baseAmount = 5,
      },
    },
  },
  {
    id = "enchanting__dawn_shatter_q2__midnight_1",
    name = "Dawn Shatter",
    patchTag = "midnight-1",
    recipeID = 1280401,
    formulaProfile = "ench_shatter",
    inputs = {
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        baseAmount = 3,
      },
    },
    rankVariants = {
      highest = {
        inputs = {
          {
            itemRef = "Dawn Crystal",
            itemIDs = { 243606 },
            amount = 1,
          },
        },
        outputs = {
          {
            itemRef = "Radiant Shard",
            itemIDs = { 243603 },
            baseAmount = 2.199,
          },
          {
            itemRef = "Radiant Shard",
            itemIDs = { 243602 },
            baseAmount = 0.801,
          },
        },
      },
      lowest = {
        inputs = {
          {
            itemRef = "Dawn Crystal",
            itemIDs = { 243605 },
            amount = 1,
          },
        },
        outputs = {
          {
            itemRef = "Radiant Shard",
            itemIDs = { 243602 },
            baseAmount = 3,
          },
        },
      },
    },
  },
  {
    id = "enchanting__radiant_shatter_q2__midnight_1",
    name = "Radiant Shatter",
    patchTag = "midnight-1",
    recipeID = 1280394,
    formulaProfile = "ench_shatter",
    inputs = {
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        baseAmount = 3,
      },
    },
    rankVariants = {
      highest = {
        inputs = {
          {
            itemRef = "Radiant Shard",
            itemIDs = { 243603 },
            amount = 1,
          },
        },
        outputs = {
          {
            itemRef = "Eversinging Dust",
            itemIDs = { 243600 },
            baseAmount = 2.199,
          },
          {
            itemRef = "Eversinging Dust",
            itemIDs = { 243599 },
            baseAmount = 0.801,
          },
        },
      },
      lowest = {
        inputs = {
          {
            itemRef = "Radiant Shard",
            itemIDs = { 243602 },
            amount = 1,
          },
        },
        outputs = {
          {
            itemRef = "Eversinging Dust",
            itemIDs = { 243599 },
            baseAmount = 3,
          },
        },
      },
    },
  },
  {
    id = "enchanting__enchant_chest_mark_of_nalorakk__midnight_1",
    name = "Enchant Chest - Mark of Nalorakk",
    patchTag = "midnight-1",
    recipeID = 1236054,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Chest - Mark of Nalorakk",
        itemIDs = { 243946, 243947 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_hex_of_leeching__midnight_1",
    name = "Enchant Helm - Hex of Leeching",
    patchTag = "midnight-1",
    recipeID = 1236055,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Hex of Leeching",
        itemIDs = { 243948, 243949 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_empowered_hex_of_leeching__midnight_1",
    name = "Enchant Helm - Empowered Hex of Leeching",
    patchTag = "midnight-1",
    recipeID = 1236056,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Empowered Hex of Leeching",
        itemIDs = { 243950, 243951 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_boots_lynxs_dexterity__midnight_1",
    name = "Enchant Boots - Lynx's Dexterity",
    patchTag = "midnight-1",
    recipeID = 1236057,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 10,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Boots - Lynx's Dexterity",
        itemIDs = { 243952, 243953 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_amani_mastery__midnight_1",
    name = "Enchant Ring - Amani Mastery",
    patchTag = "midnight-1",
    recipeID = 1236058,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Amani Mastery",
        itemIDs = { 243954, 243955 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_eyes_of_the_eagle__midnight_1",
    name = "Enchant Ring - Eyes of the Eagle",
    patchTag = "midnight-1",
    recipeID = 1236059,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 15,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 2,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Eyes of the Eagle",
        itemIDs = { 243956, 243957 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_zuljins_mastery__midnight_1",
    name = "Enchant Ring - Zul'jin's Mastery",
    patchTag = "midnight-1",
    recipeID = 1236060,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Zul'jin's Mastery",
        itemIDs = { 243958, 243959 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_flight_of_the_eagle__midnight_1",
    name = "Enchant Shoulders - Flight of the Eagle",
    patchTag = "midnight-1",
    recipeID = 1236061,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Flight of the Eagle",
        itemIDs = { 243960, 243961 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_akilzons_swiftness__midnight_1",
    name = "Enchant Shoulders - Akil'zon's Swiftness",
    patchTag = "midnight-1",
    recipeID = 1236062,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Akil'zon's Swiftness",
        itemIDs = { 243962, 243963 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_amani_perception__midnight_1",
    name = "Enchant Tool - Amani Perception",
    patchTag = "midnight-1",
    recipeID = 1236063,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Amani Perception",
        itemIDs = { 243964, 243965 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_amani_resourcefulness__midnight_1",
    name = "Enchant Tool - Amani Resourcefulness",
    patchTag = "midnight-1",
    recipeID = 1236064,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Amani Resourcefulness",
        itemIDs = { 243966, 243967 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_strength_of_halazzi__midnight_1",
    name = "Enchant Weapon - Strength of Halazzi",
    patchTag = "midnight-1",
    recipeID = 1236065,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 5,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Strength of Halazzi",
        itemIDs = { 243968, 243969 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_janalais_precision__midnight_1",
    name = "Enchant Weapon - Jan'alai's Precision",
    patchTag = "midnight-1",
    recipeID = 1236066,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Majestic Fin",
        itemIDs = { 238530 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 5,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Jan'alai's Precision",
        itemIDs = { 243970, 243971 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_berserkers_rage__midnight_1",
    name = "Enchant Weapon - Berserker's Rage",
    patchTag = "midnight-1",
    recipeID = 1236067,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Berserker's Rage",
        itemIDs = { 243972, 243973 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_chest_mark_of_the_rootwarden__midnight_1",
    name = "Enchant Chest - Mark of the Rootwarden",
    patchTag = "midnight-1",
    recipeID = 1236068,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Majestic Fin",
        itemIDs = { 238530 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Chest - Mark of the Rootwarden",
        itemIDs = { 243974, 243975 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_chest_mark_of_the_worldsoul__midnight_1",
    name = "Enchant Chest - Mark of the Worldsoul",
    patchTag = "midnight-1",
    recipeID = 1236069,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Majestic Hide",
        itemIDs = { 238529 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Chest - Mark of the Worldsoul",
        itemIDs = { 243976, 243977 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_blessing_of_speed__midnight_1",
    name = "Enchant Helm - Blessing of Speed",
    patchTag = "midnight-1",
    recipeID = 1236070,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Blessing of Speed",
        itemIDs = { 243978, 243979 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_empowered_blessing_of_speed__midnight_1",
    name = "Enchant Helm - Empowered Blessing of Speed",
    patchTag = "midnight-1",
    recipeID = 1236071,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 20,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Empowered Blessing of Speed",
        itemIDs = { 243980, 243981 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_boots_shaladrassils_roots__midnight_1",
    name = "Enchant Boots - Shaladrassil's Roots",
    patchTag = "midnight-1",
    recipeID = 1236072,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 10,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 20,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 5,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Boots - Shaladrassil's Roots",
        itemIDs = { 243982, 243983 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_natures_wrath__midnight_1",
    name = "Enchant Ring - Nature's Wrath",
    patchTag = "midnight-1",
    recipeID = 1236073,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Nature's Wrath",
        itemIDs = { 243984, 243985 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_natures_fury__midnight_1",
    name = "Enchant Ring - Nature's Fury",
    patchTag = "midnight-1",
    recipeID = 1236074,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Nature's Fury",
        itemIDs = { 243986, 243987 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_natures_grace__midnight_1",
    name = "Enchant Shoulders - Nature's Grace",
    patchTag = "midnight-1",
    recipeID = 1236075,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Nature's Grace",
        itemIDs = { 243988, 243989 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_amirdrassils_grace__midnight_1",
    name = "Enchant Shoulders - Amirdrassil's Grace",
    patchTag = "midnight-1",
    recipeID = 1236076,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 20,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Amirdrassil's Grace",
        itemIDs = { 243990, 243991 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_haranir_finesse__midnight_1",
    name = "Enchant Tool - Haranir Finesse",
    patchTag = "midnight-1",
    recipeID = 1236077,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 20,
      },
      {
        itemRef = "Refulgent Copper Ingot",
        itemIDs = { 238197, 238198 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Haranir Finesse",
        itemIDs = { 243992, 243993 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_haranir_multicrafting__midnight_1",
    name = "Enchant Tool - Haranir Multicrafting",
    patchTag = "midnight-1",
    recipeID = 1236078,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 20,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Haranir Multicrafting",
        itemIDs = { 243994, 243995 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_worldsoul_cradle__midnight_1",
    name = "Enchant Weapon - Worldsoul Cradle",
    patchTag = "midnight-1",
    recipeID = 1236079,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Worldsoul Cradle",
        itemIDs = { 243996, 243997 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_worldsoul_aegis__midnight_1",
    name = "Enchant Weapon - Worldsoul Aegis",
    patchTag = "midnight-1",
    recipeID = 1236080,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Worldsoul Aegis",
        itemIDs = { 243998, 243999 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_worldsoul_tenacity__midnight_1",
    name = "Enchant Weapon - Worldsoul Tenacity",
    patchTag = "midnight-1",
    recipeID = 1236081,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Worldsoul Tenacity",
        itemIDs = { 244000, 244001 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_chest_mark_of_the_magister__midnight_1",
    name = "Enchant Chest - Mark of the Magister",
    patchTag = "midnight-1",
    recipeID = 1236082,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Chest - Mark of the Magister",
        itemIDs = { 244002, 244003 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_rune_of_avoidance__midnight_1",
    name = "Enchant Helm - Rune of Avoidance",
    patchTag = "midnight-1",
    recipeID = 1236083,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Rune of Avoidance",
        itemIDs = { 244004, 244005 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_helm_empowered_rune_of_avoidance__midnight_1",
    name = "Enchant Helm - Empowered Rune of Avoidance",
    patchTag = "midnight-1",
    recipeID = 1236084,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 20,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Helm - Empowered Rune of Avoidance",
        itemIDs = { 244006, 244007 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_boots_farstriders_hunt__midnight_1",
    name = "Enchant Boots - Farstrider's Hunt",
    patchTag = "midnight-1",
    recipeID = 1236085,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 10,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Boots - Farstrider's Hunt",
        itemIDs = { 244008, 244009 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_thalassian_haste__midnight_1",
    name = "Enchant Ring - Thalassian Haste",
    patchTag = "midnight-1",
    recipeID = 1236086,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Thalassian Haste",
        itemIDs = { 244010, 244011 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_thalassian_versatility__midnight_1",
    name = "Enchant Ring - Thalassian Versatility",
    patchTag = "midnight-1",
    recipeID = 1236087,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Thalassian Versatility",
        itemIDs = { 244012, 244013 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_silvermoons_alacrity__midnight_1",
    name = "Enchant Ring - Silvermoon's Alacrity",
    patchTag = "midnight-1",
    recipeID = 1236088,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Silvermoon's Alacrity",
        itemIDs = { 244014, 244015 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_ring_silvermoons_tenacity__midnight_1",
    name = "Enchant Ring - Silvermoon's Tenacity",
    patchTag = "midnight-1",
    recipeID = 1236089,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 15,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Ring - Silvermoon's Tenacity",
        itemIDs = { 244016, 244017 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_thalassian_recovery__midnight_1",
    name = "Enchant Shoulders - Thalassian Recovery",
    patchTag = "midnight-1",
    recipeID = 1236090,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Thalassian Recovery",
        itemIDs = { 244018, 244019 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_shoulders_silvermoons_mending__midnight_1",
    name = "Enchant Shoulders - Silvermoon's Mending",
    patchTag = "midnight-1",
    recipeID = 1236091,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 20,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Shoulders - Silvermoon's Mending",
        itemIDs = { 244020, 244021 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_sindorei_deftness__midnight_1",
    name = "Enchant Tool - Sin'dorei Deftness",
    patchTag = "midnight-1",
    recipeID = 1236092,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 20,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Sin'dorei Deftness",
        itemIDs = { 244022, 244023 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_tool_rendorei_ingenuity__midnight_1",
    name = "Enchant Tool - Ren'dorei Ingenuity",
    patchTag = "midnight-1",
    recipeID = 1236093,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 20,
      },
      {
        itemRef = "Gloaming Alloy",
        itemIDs = { 238202, 238203 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Tool - Ren'dorei Ingenuity",
        itemIDs = { 244024, 244025 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_flames_of_the_sindorei__midnight_1",
    name = "Enchant Weapon - Flames of the Sin'dorei",
    patchTag = "midnight-1",
    recipeID = 1236094,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 25,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Flames of the Sin'dorei",
        itemIDs = { 244026, 244027 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_acuity_of_the_rendorei__midnight_1",
    name = "Enchant Weapon - Acuity of the Ren'dorei",
    patchTag = "midnight-1",
    recipeID = 1236095,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Acuity of the Ren'dorei",
        itemIDs = { 244028, 244029 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__enchant_weapon_arcane_mastery__midnight_1",
    name = "Enchant Weapon - Arcane Mastery",
    patchTag = "midnight-1",
    recipeID = 1236097,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Enchant Weapon - Arcane Mastery",
        itemIDs = { 244030, 244031 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__illusory_adornment_blooming_light__midnight_1",
    name = "Illusory Adornment - Blooming Light",
    patchTag = "midnight-1",
    recipeID = 1236098,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Enchanting Vellum",
        itemIDs = { 38682 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Illusory Adornment - Blooming Light",
        itemIDs = { 244032, 244033 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__illusory_adornment_natures_embrace__midnight_1",
    name = "Illusory Adornment - Nature's Embrace",
    patchTag = "midnight-1",
    recipeID = 1236099,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Enchanting Vellum",
        itemIDs = { 38682 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Illusory Adornment - Nature's Embrace",
        itemIDs = { 244034, 244035 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__illusory_adornment_voidtouched__midnight_1",
    name = "Illusory Adornment - Voidtouched",
    patchTag = "midnight-1",
    recipeID = 1236100,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Enchanting Vellum",
        itemIDs = { 38682 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Illusory Adornment - Voidtouched",
        itemIDs = { 244036, 244037 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_blood_elf__midnight_1",
    name = "Gleeful Glamour - Blood Elf",
    patchTag = "midnight-1",
    recipeID = 1236461,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Blood Elf",
        itemIDs = { 243773 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_dark_iron_dwarf__midnight_1",
    name = "Gleeful Glamour - Dark Iron Dwarf",
    patchTag = "midnight-1",
    recipeID = 1236463,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Dark Iron Dwarf",
        itemIDs = { 243774 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_haranir__midnight_1",
    name = "Gleeful Glamour - Haranir",
    patchTag = "midnight-1",
    recipeID = 1236464,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Haranir",
        itemIDs = { 244056 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_draenei__midnight_1",
    name = "Gleeful Glamour - Draenei",
    patchTag = "midnight-1",
    recipeID = 1236465,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Draenei",
        itemIDs = { 243775 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_dwarf__midnight_1",
    name = "Gleeful Glamour - Dwarf",
    patchTag = "midnight-1",
    recipeID = 1236466,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Dwarf",
        itemIDs = { 243776 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_gnome__midnight_1",
    name = "Gleeful Glamour - Gnome",
    patchTag = "midnight-1",
    recipeID = 1236467,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Gnome",
        itemIDs = { 243778 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_goblin__midnight_1",
    name = "Gleeful Glamour - Goblin",
    patchTag = "midnight-1",
    recipeID = 1236468,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Goblin",
        itemIDs = { 243779 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_highmountain_tauren__midnight_1",
    name = "Gleeful Glamour - Highmountain Tauren",
    patchTag = "midnight-1",
    recipeID = 1236469,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Highmountain Tauren",
        itemIDs = { 243780 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_human__midnight_1",
    name = "Gleeful Glamour - Human",
    patchTag = "midnight-1",
    recipeID = 1236470,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Human",
        itemIDs = { 243781 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_kul_tiran__midnight_1",
    name = "Gleeful Glamour - Kul Tiran",
    patchTag = "midnight-1",
    recipeID = 1236471,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Kul Tiran",
        itemIDs = { 243782 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_lightforged_draenei__midnight_1",
    name = "Gleeful Glamour - Lightforged Draenei",
    patchTag = "midnight-1",
    recipeID = 1236472,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Lightforged Draenei",
        itemIDs = { 243783 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_maghar_orc__midnight_1",
    name = "Gleeful Glamour - Mag'har Orc",
    patchTag = "midnight-1",
    recipeID = 1236473,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Mag'har Orc",
        itemIDs = { 243784 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_mechagnome__midnight_1",
    name = "Gleeful Glamour - Mechagnome",
    patchTag = "midnight-1",
    recipeID = 1236474,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Mechagnome",
        itemIDs = { 243785 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_night_elf__midnight_1",
    name = "Gleeful Glamour - Night Elf",
    patchTag = "midnight-1",
    recipeID = 1236475,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Night Elf",
        itemIDs = { 243786 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_nightborne__midnight_1",
    name = "Gleeful Glamour - Nightborne",
    patchTag = "midnight-1",
    recipeID = 1236476,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Nightborne",
        itemIDs = { 243787 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_orc__midnight_1",
    name = "Gleeful Glamour - Orc",
    patchTag = "midnight-1",
    recipeID = 1236477,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Orc",
        itemIDs = { 243788 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_pandaren__midnight_1",
    name = "Gleeful Glamour - Pandaren",
    patchTag = "midnight-1",
    recipeID = 1236478,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Pandaren",
        itemIDs = { 243789 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_tauren__midnight_1",
    name = "Gleeful Glamour - Tauren",
    patchTag = "midnight-1",
    recipeID = 1236479,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Tauren",
        itemIDs = { 243790 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_troll__midnight_1",
    name = "Gleeful Glamour - Troll",
    patchTag = "midnight-1",
    recipeID = 1236480,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Troll",
        itemIDs = { 243791 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_undead__midnight_1",
    name = "Gleeful Glamour - Undead",
    patchTag = "midnight-1",
    recipeID = 1236481,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Undead",
        itemIDs = { 243792 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_void_elf__midnight_1",
    name = "Gleeful Glamour - Void Elf",
    patchTag = "midnight-1",
    recipeID = 1236482,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Void Elf",
        itemIDs = { 243793 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_vulpera__midnight_1",
    name = "Gleeful Glamour - Vulpera",
    patchTag = "midnight-1",
    recipeID = 1236483,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Vulpera",
        itemIDs = { 243794 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_worgen__midnight_1",
    name = "Gleeful Glamour - Worgen",
    patchTag = "midnight-1",
    recipeID = 1236484,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Worgen",
        itemIDs = { 243795 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_zandalari_troll__midnight_1",
    name = "Gleeful Glamour - Zandalari Troll",
    patchTag = "midnight-1",
    recipeID = 1236485,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Zandalari Troll",
        itemIDs = { 243796 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__runed_refulgent_copper_rod__midnight_1",
    name = "Runed Refulgent Copper Rod",
    patchTag = "midnight-1",
    recipeID = 1236486,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Refulgent Copper Rod",
        itemIDs = { 244174 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Runed Refulgent Copper Rod",
        itemIDs = { 244175 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__runed_brilliant_silver_rod__midnight_1",
    name = "Runed Brilliant Silver Rod",
    patchTag = "midnight-1",
    recipeID = 1236487,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Brilliant Silver Ore",
        itemIDs = { 237364, 237365 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 5,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 2,
      },
      {
        itemRef = "Silvermoon Weapon Wrap",
        itemIDs = { 244637, 244638 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Runed Brilliant Silver Rod",
        itemIDs = { 244176 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__runed_dazzling_thorium_rod__midnight_1",
    name = "Runed Dazzling Thorium Rod",
    patchTag = "midnight-1",
    recipeID = 1236488,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Fused Vitality",
        itemIDs = { 245345 },
        amount = 20,
      },
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 3,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 30,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 4,
      },
      {
        itemRef = "Silvermoon Weapon Wrap",
        itemIDs = { 244637, 244638 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Runed Dazzling Thorium Rod",
        itemIDs = { 244177 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__thalassian_spellweavers_wand__midnight_1",
    name = "Thalassian Spellweaver's Wand",
    patchTag = "midnight-1",
    recipeID = 1236489,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 15,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Spellweaver's Wand",
        itemIDs = { 244178 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__magisters_grand_focus__midnight_1",
    name = "Magister's Grand Focus",
    patchTag = "midnight-1",
    recipeID = 1236490,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 10,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 20,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 1,
      },
      {
        itemRef = "Silvermoon Weapon Wrap",
        itemIDs = { 244637, 244638 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Magister's Grand Focus",
        itemIDs = { 244179 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__animated_sindorei_pick__midnight_1",
    name = "Animated Sin'dorei Pick",
    patchTag = "midnight-1",
    recipeID = 1246902,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 10,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 14,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Animated Sin'dorei Pick",
        itemIDs = { 262458 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__rendorei_postal_repository__midnight_1",
    name = "Ren'dorei Postal Repository",
    patchTag = "midnight-1",
    recipeID = 1246903,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 10,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 20,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 18,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 5,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Ren'dorei Postal Repository",
        itemIDs = { 262468 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__ensorcelled_broom__midnight_1",
    name = "Ensorcelled Broom",
    patchTag = "midnight-1",
    recipeID = 1246904,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 50,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 22,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 30,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 5,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Ensorcelled Broom",
        itemIDs = { 262450 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__font_of_gleaming_water__midnight_1",
    name = "Font of Gleaming Water",
    patchTag = "midnight-1",
    recipeID = 1246905,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 10,
      },
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 10,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 14,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 5,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 30,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Font of Gleaming Water",
        itemIDs = { 262455 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__animated_sindorei_hammer__midnight_1",
    name = "Animated Sin'dorei Hammer",
    patchTag = "midnight-1",
    recipeID = 1246906,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Luminant Flux",
        itemIDs = { 243060 },
        amount = 10,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 14,
      },
      {
        itemRef = "Sterling Alloy",
        itemIDs = { 238204, 238205 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Animated Sin'dorei Hammer",
        itemIDs = { 262459 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__spellbound_tome_of_thalassian_magics__midnight_1",
    name = "Spellbound Tome of Thalassian Magics",
    patchTag = "midnight-1",
    recipeID = 1246907,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 10,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 20,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 20,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 20,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Spellbound Tome of Thalassian Magics",
        itemIDs = { 262470 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__rootflame_campfire__midnight_1",
    name = "Rootflame Campfire",
    patchTag = "midnight-1",
    recipeID = 1246908,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 10,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 32,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 15,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Rootflame Campfire",
        itemIDs = { 262590 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__endless_codex_of_blooming_light__midnight_1",
    name = "Endless Codex of Blooming Light",
    patchTag = "midnight-1",
    recipeID = 1281342,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 50,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 20,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 50,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 50,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Endless Codex of Blooming Light",
        itemIDs = { 268038 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__endless_codex_of_natures_grace__midnight_1",
    name = "Endless Codex of Nature's Grace",
    patchTag = "midnight-1",
    recipeID = 1281348,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 50,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 50,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 50,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Endless Codex of Nature's Grace",
        itemIDs = { 268039 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__endless_codex_of_the_voidtouched__midnight_1",
    name = "Endless Codex of the Voidtouched",
    patchTag = "midnight-1",
    recipeID = 1281349,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 50,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 20,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 50,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 50,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Endless Codex of the Voidtouched",
        itemIDs = { 268041 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__gleeful_glamour_earthen__midnight_1",
    name = "Gleeful Glamour - Earthen",
    patchTag = "midnight-1",
    recipeID = 1236594,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599, 243600 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gleeful Glamour - Earthen",
        itemIDs = { 243777 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "enchanting__self_pouring_thalassian_sunwine__midnight_1",
    name = "Self-Pouring Thalassian Sunwine",
    patchTag = "midnight-1",
    recipeID = 1246909,
    formulaProfile = "ench_craft",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 18,
      },
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        amount = 5,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 10,
      },
      {
        itemRef = "Dawn Crystal",
        itemIDs = { 243605, 243606 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Self-Pouring Thalassian Sunwine",
        itemIDs = { 246693 },
        baseAmount = 1,
      },
    },
  },
}
