-- GoldAdvisorMidnight/Data/Professions/Inscription.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Inscription"] = {
  {
    id = "inscription__tranquility_bloom_milling__midnight_1",
    name = "Tranquility Bloom Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__argentleaf_milling__midnight_1",
    name = "Argentleaf Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Argentleaf Pigment",
        itemIDs = { 245803, 245804 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__sanguithorn_milling__midnight_1",
    name = "Sanguithorn Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Sanguithorn Pigment",
        itemIDs = { 245865, 245864 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__mana_lily_milling__midnight_1",
    name = "Mana Lily Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__sienna_ink__midnight_1",
    name = "Sienna Ink",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        amount = 20,
      },
      {
        itemRef = "Argentleaf Pigment",
        itemIDs = { 245803, 245804 },
        amount = 10,
      },
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
        excludeFromCost = true,
      },
    },
    outputs = {
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "inscription__munsell_ink__midnight_1",
    name = "Munsell Ink",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        amount = 20,
      },
      {
        itemRef = "Sanguithorn Pigment",
        itemIDs = { 245865, 245864 },
        amount = 10,
      },
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
        excludeFromCost = true,
      },
    },
    outputs = {
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "inscription__soul_cipher__midnight_1",
    name = "Soul Cipher",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        baseAmount = 1.5,
      },
    },
  },
  {
    id = "inscription__codified_azeroot__midnight_1",
    name = "Codified Azeroot",
    patchTag = "midnight-1",
    formulaProfile = "insc_codified",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__aurora_missive__midnight_1",
    name = "Thalassian Missive of the Aurora",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Aurora",
        itemIDs = { 245781, 245782 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__feverflare_missive__midnight_1",
    name = "Thalassian Missive of the Feverflare",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Feverflare",
        itemIDs = { 245783, 245784 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__fireflash_missive__midnight_1",
    name = "Thalassian Missive of the Fireflash",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Fireflash",
        itemIDs = { 245785, 245786 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__harmonious_missive__midnight_1",
    name = "Thalassian Missive of the Harmonious",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Harmonious",
        itemIDs = { 245787, 245788 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__peerless_missive__midnight_1",
    name = "Thalassian Missive of the Peerless",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Peerless",
        itemIDs = { 245789, 245790 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__quickblade_missive__midnight_1",
    name = "Thalassian Missive of the Quickblade",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Quickblade",
        itemIDs = { 245791, 245792 },
        baseAmount = 1,
      },
    },
  },
}
