-- GoldAdvisorMidnight/Data/Professions/Inscription.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Inscription"] = {
  {
    id = "inscription__tranquility_bloom_milling__midnight_1",
    name = "Tranquility Bloom Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Tranquility Bloom",
        itemIDs = { 236761, 236767 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__argentleaf_milling__midnight_1",
    name = "Argentleaf Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Argentleaf",
        itemIDs = { 236776, 236777 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Argentleaf Pigment",
        itemIDs = { 245803, 245804 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__sanguithorn_milling__midnight_1",
    name = "Sanguithorn Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Sanguithorn",
        itemIDs = { 236770, 236771 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Sanguithorn Pigment",
        itemIDs = { 245865, 245864 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__mana_lily_milling__midnight_1",
    name = "Mana Lily Milling",
    patchTag = "midnight-1",
    formulaProfile = "insc_milling",
    inputs = {
      {
        itemRef = "Mana Lily",
        itemIDs = { 236778, 236779 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        baseAmount = 13,
      },
    },
  },
  {
    id = "inscription__sienna_ink__midnight_1",
    name = "Sienna Ink",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        amount = 20,
      },
      {
        itemRef = "Argentleaf Pigment",
        itemIDs = { 245803, 245804 },
        amount = 10,
      },
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
        excludeFromCost = true,
      },
    },
    outputs = {
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "inscription__munsell_ink__midnight_1",
    name = "Munsell Ink",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Powder Pigment",
        itemIDs = { 245807, 245808 },
        amount = 20,
      },
      {
        itemRef = "Sanguithorn Pigment",
        itemIDs = { 245865, 245864 },
        amount = 10,
      },
      {
        itemRef = "Mana Lily Pigment",
        itemIDs = { 245867, 245866 },
        amount = 5,
      },
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
        excludeFromCost = true,
      },
    },
    outputs = {
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "inscription__soul_cipher__midnight_1",
    name = "Soul Cipher",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        baseAmount = 1.5,
      },
    },
  },
  {
    id = "inscription__codified_azeroot__midnight_1",
    name = "Codified Azeroot",
    patchTag = "midnight-1",
    formulaProfile = "insc_codified",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__aurora_missive__midnight_1",
    name = "Thalassian Missive of the Aurora",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Aurora",
        itemIDs = { 245781, 245782 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__feverflare_missive__midnight_1",
    name = "Thalassian Missive of the Feverflare",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Feverflare",
        itemIDs = { 245783, 245784 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__fireflash_missive__midnight_1",
    name = "Thalassian Missive of the Fireflash",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Fireflash",
        itemIDs = { 245785, 245786 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__harmonious_missive__midnight_1",
    name = "Thalassian Missive of the Harmonious",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Harmonious",
        itemIDs = { 245787, 245788 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__peerless_missive__midnight_1",
    name = "Thalassian Missive of the Peerless",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Peerless",
        itemIDs = { 245789, 245790 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__quickblade_missive__midnight_1",
    name = "Thalassian Missive of the Quickblade",
    patchTag = "midnight-1",
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of the Quickblade",
        itemIDs = { 245791, 245792 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__hobbyist_rolling_pin__midnight_1",
    name = "Hobbyist Rolling Pin",
    patchTag = "midnight-1",
    recipeID = 1230020,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 10,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Hobbyist Rolling Pin",
        itemIDs = { 245779 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__hobbyist_alchemists_mixing_rod__midnight_1",
    name = "Hobbyist Alchemist's Mixing Rod",
    patchTag = "midnight-1",
    recipeID = 1230021,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 10,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Hobbyist Alchemist's Mixing Rod",
        itemIDs = { 245777 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__hobbyist_scribes_quill__midnight_1",
    name = "Hobbyist Scribe's Quill",
    patchTag = "midnight-1",
    recipeID = 1230022,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 5,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Hobbyist Scribe's Quill",
        itemIDs = { 245775 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__sindorei_rolling_pin__midnight_1",
    name = "Sin'dorei Rolling Pin",
    patchTag = "midnight-1",
    recipeID = 1230023,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Rolling Pin",
        itemIDs = { 245780 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__sindorei_alchemists_mixing_rod__midnight_1",
    name = "Sin'dorei Alchemist's Mixing Rod",
    patchTag = "midnight-1",
    recipeID = 1230024,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 6,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Alchemist's Mixing Rod",
        itemIDs = { 245778 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__sindorei_quill__midnight_1",
    name = "Sin'dorei Quill",
    patchTag = "midnight-1",
    recipeID = 1230025,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 5,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 5,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Quill",
        itemIDs = { 245776 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_blacksmithing__midnight_1",
    name = "Thalassian Treatise on Blacksmithing",
    patchTag = "midnight-1",
    recipeID = 1230026,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Blacksmithing",
        itemIDs = { 245763 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_mining__midnight_1",
    name = "Thalassian Treatise on Mining",
    patchTag = "midnight-1",
    recipeID = 1230027,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Mining",
        itemIDs = { 245762 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_herbalism__midnight_1",
    name = "Thalassian Treatise on Herbalism",
    patchTag = "midnight-1",
    recipeID = 1230028,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Herbalism",
        itemIDs = { 245761 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_jewelcrafting__midnight_1",
    name = "Thalassian Treatise on Jewelcrafting",
    patchTag = "midnight-1",
    recipeID = 1230029,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Jewelcrafting",
        itemIDs = { 245760 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_enchanting__midnight_1",
    name = "Thalassian Treatise on Enchanting",
    patchTag = "midnight-1",
    recipeID = 1230030,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Enchanting",
        itemIDs = { 245759 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_leatherworking__midnight_1",
    name = "Thalassian Treatise on Leatherworking",
    patchTag = "midnight-1",
    recipeID = 1230031,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Leatherworking",
        itemIDs = { 245758 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_inscription__midnight_1",
    name = "Thalassian Treatise on Inscription",
    patchTag = "midnight-1",
    recipeID = 1230032,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Inscription",
        itemIDs = { 245757 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_tailoring__midnight_1",
    name = "Thalassian Treatise on Tailoring",
    patchTag = "midnight-1",
    recipeID = 1230033,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Tailoring",
        itemIDs = { 245756 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_alchemy__midnight_1",
    name = "Thalassian Treatise on Alchemy",
    patchTag = "midnight-1",
    recipeID = 1230034,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Alchemy",
        itemIDs = { 245755 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_skinning__midnight_1",
    name = "Thalassian Treatise on Skinning",
    patchTag = "midnight-1",
    recipeID = 1230035,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Skinning",
        itemIDs = { 245828 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_treatise_on_engineering__midnight_1",
    name = "Thalassian Treatise on Engineering",
    patchTag = "midnight-1",
    recipeID = 1230036,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 3,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Treatise on Engineering",
        itemIDs = { 245809 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_deftness__midnight_1",
    name = "Thalassian Missive of Deftness",
    patchTag = "midnight-1",
    recipeID = 1230043,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Deftness",
        itemIDs = { 245826, 245827 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_perception__midnight_1",
    name = "Thalassian Missive of Perception",
    patchTag = "midnight-1",
    recipeID = 1230044,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Perception",
        itemIDs = { 245824, 245825 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_finesse__midnight_1",
    name = "Thalassian Missive of Finesse",
    patchTag = "midnight-1",
    recipeID = 1230045,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Finesse",
        itemIDs = { 245822, 245823 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_crafting_speed__midnight_1",
    name = "Thalassian Missive of Crafting Speed",
    patchTag = "midnight-1",
    recipeID = 1230046,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Crafting Speed",
        itemIDs = { 245820, 245821 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_multicraft__midnight_1",
    name = "Thalassian Missive of Multicraft",
    patchTag = "midnight-1",
    recipeID = 1230047,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Multicraft",
        itemIDs = { 245818, 245819 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_resourcefulness__midnight_1",
    name = "Thalassian Missive of Resourcefulness",
    patchTag = "midnight-1",
    recipeID = 1230048,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Resourcefulness",
        itemIDs = { 245816, 245817 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_missive_of_ingenuity__midnight_1",
    name = "Thalassian Missive of Ingenuity",
    patchTag = "midnight-1",
    recipeID = 1230049,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 1,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Missive of Ingenuity",
        itemIDs = { 245814, 245815 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__vantus_rune_radiant__midnight_1",
    name = "Vantus Rune: Radiant",
    patchTag = "midnight-1",
    recipeID = 1230050,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Vantus Rune: Radiant",
        itemIDs = { 245879 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__contract_the_silvermoon_court__midnight_1",
    name = "Contract: The Silvermoon Court",
    patchTag = "midnight-1",
    recipeID = 1230051,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Contract: The Silvermoon Court",
        itemIDs = { 245799 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__contract_the_amani_tribe__midnight_1",
    name = "Contract: The Amani Tribe",
    patchTag = "midnight-1",
    recipeID = 1230052,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Contract: The Amani Tribe",
        itemIDs = { 245797 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__contract_the_harati__midnight_1",
    name = "Contract: The Hara'ti",
    patchTag = "midnight-1",
    recipeID = 1230053,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Contract: The Hara'ti",
        itemIDs = { 245795 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__contract_the_singularity__midnight_1",
    name = "Contract: The Singularity",
    patchTag = "midnight-1",
    recipeID = 1230054,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Lexicologist's Vellum",
        itemIDs = { 245881 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 3,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 1,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Contract: The Singularity",
        itemIDs = { 245793 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__faunatenders_baton__midnight_1",
    name = "Faunatender's Baton",
    patchTag = "midnight-1",
    recipeID = 1230055,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Faunatender's Baton",
        itemIDs = { 245773 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__floratenders_crutch__midnight_1",
    name = "Floratender's Crutch",
    patchTag = "midnight-1",
    recipeID = 1230056,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Floratender's Crutch",
        itemIDs = { 245772 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__rootwardens_lamp__midnight_1",
    name = "Rootwarden's Lamp",
    patchTag = "midnight-1",
    recipeID = 1230057,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Rootwarden's Lamp",
        itemIDs = { 245768 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__faunatenders_trust__midnight_1",
    name = "Faunatender's Trust",
    patchTag = "midnight-1",
    recipeID = 1230058,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Azeroot",
        itemIDs = { 236774, 236775 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Faunatender's Trust",
        itemIDs = { 265336 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__alnhara_pikestaff__midnight_1",
    name = "Aln'hara Pikestaff",
    patchTag = "midnight-1",
    recipeID = 1230059,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Majestic Hide",
        itemIDs = { 238529 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 6,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Aln'hara Pikestaff",
        itemIDs = { 245771 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__alnhara_cane__midnight_1",
    name = "Aln'hara Cane",
    patchTag = "midnight-1",
    recipeID = 1230060,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Majestic Hide",
        itemIDs = { 238529 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 6,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Aln'hara Cane",
        itemIDs = { 245770 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__alnhara_lantern__midnight_1",
    name = "Aln'hara Lantern",
    patchTag = "midnight-1",
    recipeID = 1230061,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Majestic Claw",
        itemIDs = { 238528 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Aln'hara Lantern",
        itemIDs = { 245769 },
        baseAmount = 1,
      },
    },
  },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "inscription__alnhara_sprigshot__midnight_1",
--     name = "Aln'hara Sprigshot",
--     patchTag = "midnight-1",
--     recipeID = 1230062,
--     formulaProfile = "insc_ink",
--     inputs = {
--       {
--         itemRef = "Majestic Fin",
--         itemIDs = { 238530 },
--         amount = 1,
--       },
--       {
--         itemRef = "Tormented Tantalum",
--         itemIDs = { 251283 },
--         amount = 1,
--       },
--       {
--         itemRef = "Codified Azeroot",
--         itemIDs = { 245764, 245765 },
--         amount = 8,
--       },
--       {
--         itemRef = "Soul Cipher",
--         itemIDs = { 245766, 245767 },
--         amount = 2,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Aln'hara Sprigshot",
--         itemIDs = { 265337 },
--         baseAmount = 1,
--       },
--     },
--   },
  {
    id = "inscription__thalassian_competitors_lamp__midnight_1",
    name = "Thalassian Competitor's Lamp",
    patchTag = "midnight-1",
    recipeID = 1230064,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 2,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Lamp",
        itemIDs = { 245870 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_staff__midnight_1",
    name = "Thalassian Competitor's Staff",
    patchTag = "midnight-1",
    recipeID = 1230065,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Staff",
        itemIDs = { 268365 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_pillar__midnight_1",
    name = "Thalassian Competitor's Pillar",
    patchTag = "midnight-1",
    recipeID = 1230066,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Pillar",
        itemIDs = { 245868 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_emblem__midnight_1",
    name = "Thalassian Competitor's Emblem",
    patchTag = "midnight-1",
    recipeID = 1230067,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 4,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Emblem",
        itemIDs = { 245753 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_insignia_of_alacrity__midnight_1",
    name = "Thalassian Competitor's Insignia of Alacrity",
    patchTag = "midnight-1",
    recipeID = 1230068,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 4,
      },
      {
        itemRef = "Munsell Ink",
        itemIDs = { 245801, 245802 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Insignia of Alacrity",
        itemIDs = { 245752 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_medallion__midnight_1",
    name = "Thalassian Competitor's Medallion",
    patchTag = "midnight-1",
    recipeID = 1230069,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 3,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 4,
      },
      {
        itemRef = "Sienna Ink",
        itemIDs = { 245805, 245806 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Medallion",
        itemIDs = { 245751 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_dominion_blood__midnight_1",
    name = "Darkmoon Dominion: Blood",
    patchTag = "midnight-1",
    recipeID = 1230070,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 20,
      },
      {
        itemRef = "Darkmoon Deck: Blood",
        itemIDs = { 245855 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 10,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Dominion: Blood",
        itemIDs = { 246305 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_dominion_rot__midnight_1",
    name = "Darkmoon Dominion: Rot",
    patchTag = "midnight-1",
    recipeID = 1230071,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 20,
      },
      {
        itemRef = "Darkmoon Deck: Rot",
        itemIDs = { 245846 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 10,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Dominion: Rot",
        itemIDs = { 246306 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_dominion_hunt__midnight_1",
    name = "Darkmoon Dominion: Hunt",
    patchTag = "midnight-1",
    recipeID = 1230072,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 20,
      },
      {
        itemRef = "Darkmoon Deck: Hunt",
        itemIDs = { 245829 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 10,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Dominion: Hunt",
        itemIDs = { 246304 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_dominion_void__midnight_1",
    name = "Darkmoon Dominion: Void",
    patchTag = "midnight-1",
    recipeID = 1230073,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 20,
      },
      {
        itemRef = "Darkmoon Deck: Void",
        itemIDs = { 245750 },
        amount = 1,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 10,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Dominion: Void",
        itemIDs = { 246307 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_sigil_blood__midnight_1",
    name = "Darkmoon Sigil: Blood",
    patchTag = "midnight-1",
    recipeID = 1230074,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 10,
      },
      {
        itemRef = "Darkmoon Deck: Blood",
        itemIDs = { 245855 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Sigil: Blood",
        itemIDs = { 245871, 245872 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_sigil_rot__midnight_1",
    name = "Darkmoon Sigil: Rot",
    patchTag = "midnight-1",
    recipeID = 1230075,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 10,
      },
      {
        itemRef = "Darkmoon Deck: Rot",
        itemIDs = { 245846 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Sigil: Rot",
        itemIDs = { 245877, 245878 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_sigil_hunt__midnight_1",
    name = "Darkmoon Sigil: Hunt",
    patchTag = "midnight-1",
    recipeID = 1230076,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 10,
      },
      {
        itemRef = "Darkmoon Deck: Hunt",
        itemIDs = { 245829 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Sigil: Hunt",
        itemIDs = { 245875, 245876 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__darkmoon_sigil_void__midnight_1",
    name = "Darkmoon Sigil: Void",
    patchTag = "midnight-1",
    recipeID = 1230077,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Songwater",
        itemIDs = { 245882 },
        amount = 1,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 10,
      },
      {
        itemRef = "Darkmoon Deck: Void",
        itemIDs = { 245750 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Darkmoon Sigil: Void",
        itemIDs = { 245873, 245874 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__sturdy_rendorei_cask__midnight_1",
    name = "Sturdy Ren'dorei Cask",
    patchTag = "midnight-1",
    recipeID = 1248619,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 26,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 5,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Sturdy Ren'dorei Cask",
        itemIDs = { 262612 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__restful_bronze_bench__midnight_1",
    name = "Restful Bronze Bench",
    patchTag = "midnight-1",
    recipeID = 1248620,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 22,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Restful Bronze Bench",
        itemIDs = { 262790 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__floating_void_touched_tome__midnight_1",
    name = "Floating Void-Touched Tome",
    patchTag = "midnight-1",
    recipeID = 1248621,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 22,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Floating Void-Touched Tome",
        itemIDs = { 262464 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__homely_sindorei_shelf__midnight_1",
    name = "Homely Sin'dorei Shelf",
    patchTag = "midnight-1",
    recipeID = 1248622,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 24,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 9,
      },
    },
    outputs = {
      {
        itemRef = "Homely Sin'dorei Shelf",
        itemIDs = { 262594 },
        baseAmount = 1,
      },
    },
  },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "inscription__lively_songwriters_quill__midnight_1",
--     name = "Lively Songwriter's Quill",
--     patchTag = "midnight-1",
--     recipeID = 1248623,
--     formulaProfile = "insc_ink",
--     inputs = {
--       {
--         itemRef = "Thalassian Lumber",
--         itemIDs = { 256963 },
--         amount = 18,
--       },
--       {
--         itemRef = "Codified Azeroot",
--         itemIDs = { 245764, 245765 },
--         amount = 3,
--       },
--       {
--         itemRef = "Soul Cipher",
--         itemIDs = { 245766, 245767 },
--         amount = 7,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Lively Songwriter's Quill",
--         itemIDs = { 262616 },
--         baseAmount = 1,
--       },
--     },
--   },
  {
    id = "inscription__opened_sindorei_scroll__midnight_1",
    name = "Opened Sin'dorei Scroll",
    patchTag = "midnight-1",
    recipeID = 1248624,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 6,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Opened Sin'dorei Scroll",
        itemIDs = { 262598 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__gilded_eversong_book__midnight_1",
    name = "Gilded Eversong Book",
    patchTag = "midnight-1",
    recipeID = 1248625,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 6,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Gilded Eversong Book",
        itemIDs = { 262597 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__sindorei_phoenix_quill__midnight_1",
    name = "Sin'dorei Phoenix Quill",
    patchTag = "midnight-1",
    recipeID = 1248626,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 4,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 1,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Phoenix Quill",
        itemIDs = { 262615 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__homely_wall_shelves__midnight_1",
    name = "Homely Wall Shelves",
    patchTag = "midnight-1",
    recipeID = 1248627,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 24,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 4,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 9,
      },
    },
    outputs = {
      {
        itemRef = "Homely Wall Shelves",
        itemIDs = { 262595 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__wild_hanging_scroll__midnight_1",
    name = "Wild Hanging Scroll",
    patchTag = "midnight-1",
    recipeID = 1248628,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 18,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 3,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 7,
      },
    },
    outputs = {
      {
        itemRef = "Wild Hanging Scroll",
        itemIDs = { 262601 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__harandar_signpost__midnight_1",
    name = "Harandar Signpost",
    patchTag = "midnight-1",
    recipeID = 1248630,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 18,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 3,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 7,
      },
    },
    outputs = {
      {
        itemRef = "Harandar Signpost",
        itemIDs = { 253508 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__magnificent_towering_bookcase__midnight_1",
    name = "Magnificent Towering Bookcase",
    patchTag = "midnight-1",
    recipeID = 1248631,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 50,
      },
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 10,
      },
      {
        itemRef = "Soul Cipher",
        itemIDs = { 245766, 245767 },
        amount = 20,
      },
    },
    outputs = {
      {
        itemRef = "Magnificent Towering Bookcase",
        itemIDs = { 263034 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "inscription__thalassian_competitors_bow__midnight_1",
    name = "Thalassian Competitor's Bow",
    patchTag = "midnight-1",
    recipeID = 1260760,
    formulaProfile = "insc_ink",
    inputs = {
      {
        itemRef = "Codified Azeroot",
        itemIDs = { 245764, 245765 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Bow",
        itemIDs = { 245869 },
        baseAmount = 1,
      },
    },
  },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "inscription__gilded_alchemists_mixing_rod__midnight_1",
--     name = "Gilded Alchemist's Mixing Rod",
--     patchTag = "midnight-1",
--     recipeID = 1264550,
--     formulaProfile = "insc_ink",
--     inputs = {
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Codified Azeroot",
--         itemIDs = { 245764, 245765 },
--         amount = 10,
--       },
--       {
--         itemRef = "Soul Cipher",
--         itemIDs = { 245766, 245767 },
--         amount = 4,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Gilded Alchemist's Mixing Rod",
--         itemIDs = { 259205 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "inscription__gilded_sindorei_rolling_pin__midnight_1",
--     name = "Gilded Sin'dorei Rolling Pin",
--     patchTag = "midnight-1",
--     recipeID = 1264551,
--     formulaProfile = "insc_ink",
--     inputs = {
--       {
--         itemRef = "Majestic Claw",
--         itemIDs = { 238528 },
--         amount = 2,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Codified Azeroot",
--         itemIDs = { 245764, 245765 },
--         amount = 4,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Gilded Sin'dorei Rolling Pin",
--         itemIDs = { 259207 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "inscription__gilded_sindorei_quill__midnight_1",
--     name = "Gilded Sin'dorei Quill",
--     patchTag = "midnight-1",
--     recipeID = 1264552,
--     formulaProfile = "insc_ink",
--     inputs = {
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Codified Azeroot",
--         itemIDs = { 245764, 245765 },
--         amount = 8,
--       },
--       {
--         itemRef = "Munsell Ink",
--         itemIDs = { 245801, 245802 },
--         amount = 8,
--       },
--       {
--         itemRef = "Sienna Ink",
--         itemIDs = { 245805, 245806 },
--         amount = 8,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Gilded Sin'dorei Quill",
--         itemIDs = { 259209 },
--         baseAmount = 1,
--       },
--     },
--   },
}
