-- GoldAdvisorMidnight/Data/Professions/Jewelcrafting.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Jewelcrafting"] = {
  {
    id = "jewelcrafting__refulgent_copper_ore_prospecting__midnight_1",
    name = "Refulgent Copper Ore Prospecting",
    patchTag = "midnight-1",
    formulaProfile = "jc_prospect",
    inputs = {
      {
        itemRef = "Refulgent Copper Ore",
        itemIDs = { 237359, 237361 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        baseAmount = 0.106449,
      },
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        baseAmount = 0.106449,
      },
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        baseAmount = 0.106449,
      },
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        baseAmount = 0.106449,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        baseAmount = 0.023141,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        baseAmount = 0.925644,
      },
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        baseAmount = 0.647951,
      },
    },
  },
  {
    id = "jewelcrafting__brilliant_silver_ore_prospecting__midnight_1",
    name = "Brilliant Silver Ore Prospecting",
    patchTag = "midnight-1",
    formulaProfile = "jc_prospect",
    inputs = {
      {
        itemRef = "Brilliant Silver Ore",
        itemIDs = { 237364, 237365 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        baseAmount = 0.157359,
      },
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        baseAmount = 0.157359,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        baseAmount = 0.145326,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        baseAmount = 0.145326,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        baseAmount = 0.039803,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        baseAmount = 0.879362,
      },
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        baseAmount = 0.705341,
      },
    },
  },
  {
    id = "jewelcrafting__umbral_tin_ore_prospecting__midnight_1",
    name = "Umbral Tin Ore Prospecting",
    patchTag = "midnight-1",
    formulaProfile = "jc_prospect",
    inputs = {
      {
        itemRef = "Umbral Tin Ore",
        itemIDs = { 237362, 237363 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        baseAmount = 0.157359,
      },
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        baseAmount = 0.157359,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        baseAmount = 0.145326,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        baseAmount = 0.145326,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        baseAmount = 0.039803,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        baseAmount = 0.879362,
      },
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        baseAmount = 0.705341,
      },
    },
  },
  {
    id = "jewelcrafting__dazzling_thorium_prospecting__midnight_1",
    name = "Dazzling Thorium Prospecting",
    patchTag = "midnight-1",
    formulaProfile = "jc_prospect",
    inputs = {
      {
        itemRef = "Dazzling Thorium",
        itemIDs = { 237366 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        baseAmount = 0.175,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        baseAmount = 0.175,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        baseAmount = 0.175,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        baseAmount = 0.175,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        baseAmount = 0.2375,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        baseAmount = 1.35,
      },
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        baseAmount = 0.8,
      },
    },
  },
  {
    id = "jewelcrafting__crushing__midnight_1",
    name = "Crushing",
    patchTag = "midnight-1",
    formulaProfile = "jc_crush",
    inputs = {
      {
        itemRef = "Cheapest Gem",
        itemIDs = { 242554, 242722 },
        amount = 3,
        alternatives = {
          {
            itemRef = "Sanguine Garnet",
            itemIDs = { 242553, 242723 },
          },
          {
            itemRef = "Amani Lapis",
            itemIDs = { 242554, 242722 },
          },
          {
            itemRef = "Tenebrous Amethyst",
            itemIDs = { 242606, 242721 },
          },
          {
            itemRef = "Harandar Peridot",
            itemIDs = { 242607, 242720 },
          },
          {
            itemRef = "Eversong Diamond",
            itemIDs = { 242608, 242712 },
          },
          {
            itemRef = "Flawless Sanguine Garnet",
            itemIDs = { 242613, 242724 },
          },
          {
            itemRef = "Flawless Amani Lapis",
            itemIDs = { 242612, 242727 },
          },
          {
            itemRef = "Flawless Tenebrous Amethyst",
            itemIDs = { 242611, 242725 },
          },
          {
            itemRef = "Flawless Harandar Peridot",
            itemIDs = { 242610, 242726 },
          },
        },
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 1.05,
      },
    },
    outputs = {
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        baseAmount = 2.09,
      },
    },
  },
  {
    id = "jewelcrafting__sin_dorei_lens_crafting__midnight_1",
    name = "Sin'dorei Lens Crafting",
    patchTag = "midnight-1",
    recipeID = 1230475,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        amount = 3,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Lens",
        itemIDs = { 240972, 240973 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__sunglass_vial_crafting__midnight_1",
    name = "Sunglass Vial Crafting",
    patchTag = "midnight-1",
    recipeID = 1230476,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Crystalline Glass",
        itemIDs = { 242786, 242787 },
        amount = 5,
      },
      {
        itemRef = "Duskshrouded Stone",
        itemIDs = { 242788, 242789 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sunglass Vial",
        itemIDs = { 240990, 240991 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__quick_peridot__midnight_1",
    name = "Quick Peridot",
    patchTag = "midnight-1",
    recipeID = 1230437,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quick Peridot",
        itemIDs = { 240855, 240856 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__deadly_peridot__midnight_1",
    name = "Deadly Peridot",
    patchTag = "midnight-1",
    recipeID = 1230439,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Deadly Peridot",
        itemIDs = { 240857, 240858 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__masterful_peridot__midnight_1",
    name = "Masterful Peridot",
    patchTag = "midnight-1",
    recipeID = 1230440,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Masterful Peridot",
        itemIDs = { 240859, 240860 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__versatile_peridot__midnight_1",
    name = "Versatile Peridot",
    patchTag = "midnight-1",
    recipeID = 1230441,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Versatile Peridot",
        itemIDs = { 240861, 240862 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__versatile_lapis__midnight_1",
    name = "Versatile Lapis",
    patchTag = "midnight-1",
    recipeID = 1230449,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Versatile Lapis",
        itemIDs = { 240879, 240880 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__deadly_lapis__midnight_1",
    name = "Deadly Lapis",
    patchTag = "midnight-1",
    recipeID = 1230447,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Deadly Lapis",
        itemIDs = { 240881, 240882 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__quick_lapis__midnight_1",
    name = "Quick Lapis",
    patchTag = "midnight-1",
    recipeID = 1230446,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quick Lapis",
        itemIDs = { 240883, 240884 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__masterful_lapis__midnight_1",
    name = "Masterful Lapis",
    patchTag = "midnight-1",
    recipeID = 1230448,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Masterful Lapis",
        itemIDs = { 240885, 240886 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__masterful_amethyst__midnight_1",
    name = "Masterful Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230456,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Masterful Amethyst",
        itemIDs = { 240863, 240864 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__deadly_amethyst__midnight_1",
    name = "Deadly Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230455,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Deadly Amethyst",
        itemIDs = { 240865, 240866 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__quick_amethyst__midnight_1",
    name = "Quick Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230454,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quick Amethyst",
        itemIDs = { 240867, 240868 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__versatile_amethyst__midnight_1",
    name = "Versatile Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230457,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Versatile Amethyst",
        itemIDs = { 240869, 240870 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__deadly_garnet__midnight_1",
    name = "Deadly Garnet",
    patchTag = "midnight-1",
    recipeID = 1230463,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Deadly Garnet",
        itemIDs = { 240871, 240872 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__quick_garnet__midnight_1",
    name = "Quick Garnet",
    patchTag = "midnight-1",
    recipeID = 1230462,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Quick Garnet",
        itemIDs = { 240873, 240874 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__masterful_garnet__midnight_1",
    name = "Masterful Garnet",
    patchTag = "midnight-1",
    recipeID = 1230464,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Masterful Garnet",
        itemIDs = { 240875, 240876 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__versatile_garnet__midnight_1",
    name = "Versatile Garnet",
    patchTag = "midnight-1",
    recipeID = 1230465,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Versatile Garnet",
        itemIDs = { 240877, 240878 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_quick_peridot__midnight_1",
    name = "Flawless Quick Peridot",
    patchTag = "midnight-1",
    recipeID = 1230442,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Quick Peridot",
        itemIDs = { 240887, 240888 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_deadly_peridot__midnight_1",
    name = "Flawless Deadly Peridot",
    patchTag = "midnight-1",
    recipeID = 1230443,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Deadly Peridot",
        itemIDs = { 240889, 240890 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_masterful_peridot__midnight_1",
    name = "Flawless Masterful Peridot",
    patchTag = "midnight-1",
    recipeID = 1230444,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Masterful Peridot",
        itemIDs = { 240891, 240892 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_versatile_peridot__midnight_1",
    name = "Flawless Versatile Peridot",
    patchTag = "midnight-1",
    recipeID = 1230445,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Versatile Peridot",
        itemIDs = { 240893, 240894 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_versatile_lapis__midnight_1",
    name = "Flawless Versatile Lapis",
    patchTag = "midnight-1",
    recipeID = 1230453,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Versatile Lapis",
        itemIDs = { 240911, 240912 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_deadly_lapis__midnight_1",
    name = "Flawless Deadly Lapis",
    patchTag = "midnight-1",
    recipeID = 1230451,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Deadly Lapis",
        itemIDs = { 240913, 240914 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_quick_lapis__midnight_1",
    name = "Flawless Quick Lapis",
    patchTag = "midnight-1",
    recipeID = 1230450,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Quick Lapis",
        itemIDs = { 240915, 240916 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_masterful_lapis__midnight_1",
    name = "Flawless Masterful Lapis",
    patchTag = "midnight-1",
    recipeID = 1230452,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Masterful Lapis",
        itemIDs = { 240917, 240918 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_masterful_amethyst__midnight_1",
    name = "Flawless Masterful Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230460,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Masterful Amethyst",
        itemIDs = { 240895, 240896 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_deadly_amethyst__midnight_1",
    name = "Flawless Deadly Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230459,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Deadly Amethyst",
        itemIDs = { 240897, 240898 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_quick_amethyst__midnight_1",
    name = "Flawless Quick Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230458,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Quick Amethyst",
        itemIDs = { 240899, 240900 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_versatile_amethyst__midnight_1",
    name = "Flawless Versatile Amethyst",
    patchTag = "midnight-1",
    recipeID = 1230461,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Versatile Amethyst",
        itemIDs = { 240901, 240902 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_deadly_garnet__midnight_1",
    name = "Flawless Deadly Garnet",
    patchTag = "midnight-1",
    recipeID = 1230467,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Deadly Garnet",
        itemIDs = { 240903, 240904 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_quick_garnet__midnight_1",
    name = "Flawless Quick Garnet",
    patchTag = "midnight-1",
    recipeID = 1230466,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Quick Garnet",
        itemIDs = { 240905, 240906 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_masterful_garnet__midnight_1",
    name = "Flawless Masterful Garnet",
    patchTag = "midnight-1",
    recipeID = 1230468,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Masterful Garnet",
        itemIDs = { 240907, 240908 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__flawless_versatile_garnet__midnight_1",
    name = "Flawless Versatile Garnet",
    patchTag = "midnight-1",
    recipeID = 1230469,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 3,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 1,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 5,
      },
    },
    outputs = {
      {
        itemRef = "Flawless Versatile Garnet",
        itemIDs = { 240909, 240910 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__kaleidoscopic_prism__midnight_1",
    name = "Kaleidoscopic Prism",
    patchTag = "midnight-1",
    recipeID = 1230474,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Flawless Harandar Peridot",
        itemIDs = { 242610, 242726 },
        amount = 1,
      },
      {
        itemRef = "Flawless Tenebrous Amethyst",
        itemIDs = { 242611, 242725 },
        amount = 1,
      },
      {
        itemRef = "Flawless Amani Lapis",
        itemIDs = { 242612, 242727 },
        amount = 1,
      },
      {
        itemRef = "Flawless Sanguine Garnet",
        itemIDs = { 242613, 242724 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Kaleidoscopic Prism",
        itemIDs = { 240974, 240975 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__prismatic_focusing_iris__midnight_1",
    name = "Prismatic Focusing Iris",
    patchTag = "midnight-1",
    recipeID = 1230477,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sin'dorei Lens",
        itemIDs = { 240972, 240973 },
        amount = 2,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Prismatic Focusing Iris",
        itemIDs = { 251487, 251488 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__stabilizing_gemstone_bandolier__midnight_1",
    name = "Stabilizing Gemstone Bandolier",
    patchTag = "midnight-1",
    recipeID = 1230478,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Sanguine Garnet",
        itemIDs = { 242553, 242723 },
        amount = 1,
      },
      {
        itemRef = "Amani Lapis",
        itemIDs = { 242554, 242722 },
        amount = 1,
      },
      {
        itemRef = "Tenebrous Amethyst",
        itemIDs = { 242606, 242721 },
        amount = 1,
      },
      {
        itemRef = "Harandar Peridot",
        itemIDs = { 242607, 242720 },
        amount = 1,
      },
      {
        itemRef = "Glimmering Gemdust",
        itemIDs = { 242620, 242621 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Stabilizing Gemstone Bandolier",
        itemIDs = { 251489, 251490 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__powerful_eversong_diamond__midnight_1",
    name = "Powerful Eversong Diamond",
    patchTag = "midnight-1",
    recipeID = 1230470,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Kaleidoscopic Prism",
        itemIDs = { 240974, 240975 },
        amount = 1,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Powerful Eversong Diamond",
        itemIDs = { 240966, 240967 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__telluric_eversong_diamond__midnight_1",
    name = "Telluric Eversong Diamond",
    patchTag = "midnight-1",
    recipeID = 1230471,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Kaleidoscopic Prism",
        itemIDs = { 240974, 240975 },
        amount = 1,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Telluric Eversong Diamond",
        itemIDs = { 240968, 240969 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__stoic_eversong_diamond__midnight_1",
    name = "Stoic Eversong Diamond",
    patchTag = "midnight-1",
    recipeID = 1230472,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Kaleidoscopic Prism",
        itemIDs = { 240974, 240975 },
        amount = 1,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Stoic Eversong Diamond",
        itemIDs = { 240970, 240971 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "jewelcrafting__indecipherable_eversong_diamond__midnight_1",
    name = "Indecipherable Eversong Diamond",
    patchTag = "midnight-1",
    recipeID = 1230473,
    formulaProfile = "jc_craft",
    inputs = {
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 2,
      },
      {
        itemRef = "Kaleidoscopic Prism",
        itemIDs = { 240974, 240975 },
        amount = 1,
      },
      {
        itemRef = "Eversong Diamond",
        itemIDs = { 242608, 242712 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Indecipherable Eversong Diamond",
        itemIDs = { 240982, 240983 },
        baseAmount = 1,
      },
    },
  },
}
