-- GoldAdvisorMidnight/Data/Professions/Leatherworking.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Leatherworking"] = {
  {
    id = "leatherworking__scale_woven_hide__midnight_1",
    name = "Scale Woven Hide",
    patchTag = "midnight-1",
    formulaProfile = "leatherworking",
    inputs = {
      {
        itemRef = "Void-Tempered Hide",
        itemIDs = { 238518, 238519 },
        amount = 1,
      },
      {
        itemRef = "Void-Tempered Plating",
        itemIDs = { 238520, 238521 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Scalewoven Hide",
        itemIDs = { 244631, 244632 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "leatherworking__sin_dorei_armor_banding__midnight_1",
    name = "Sin'Dorei Armor Banding",
    patchTag = "midnight-1",
    formulaProfile = "leatherworking",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 2,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 1,
      },
      {
        itemRef = "Void-Tempered Plating",
        itemIDs = { 238520, 238521 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Sin'dorei Armor Banding",
        itemIDs = { 244635, 244636 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "leatherworking__silvermoon_weapon_wrap__midnight_1",
    name = "Silvermoon Weapon Wrap",
    patchTag = "midnight-1",
    formulaProfile = "leatherworking",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 2,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 1,
      },
      {
        itemRef = "Void-Tempered Hide",
        itemIDs = { 238518, 238519 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Silvermoon Weapon Wrap",
        itemIDs = { 244637, 244638 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "leatherworking__void_touched_drums__midnight_1",
    name = "Void-Touched Drums",
    patchTag = "midnight-1",
    formulaProfile = "leatherworking",
    inputs = {
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 1,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Void-Tempered Leather",
        itemIDs = { 238511, 238512 },
        amount = 10,
      },
      {
        itemRef = "Void-Tempered Scales",
        itemIDs = { 238513, 238514 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Void-Touched Drums",
        itemIDs = { 244639 },
        baseAmount = 1,
      },
    },
  },
}
