-- GoldAdvisorMidnight/Data/Professions/Tailoring.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Tailoring"] = {
  {
    id = "tailoring__bright_linen_bolt__midnight_1",
    name = "Bright Linen Bolt",
    patchTag = "midnight-1",
    recipeID = 1228939,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Bright Linen",
        itemIDs = { 236963, 236965 },
        amount = 1,
      },
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__imbued_bright_linen_bolt__midnight_1",
    name = "Imbued Bright Linen Bolt",
    patchTag = "midnight-1",
    recipeID = 1228940,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_bolt__midnight_1",
    name = "Arcanoweave Bolt",
    patchTag = "midnight-1",
    recipeID = 1227926,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 4,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 5,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "tailoring__sunfire_silk_bolt__midnight_1",
    name = "Sunfire Silk Bolt",
    patchTag = "midnight-1",
    recipeID = 1228060,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 4,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 5,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        baseAmount = 2,
      },
    },
  },
  {
    id = "tailoring__bright_linen_bandage__midnight_1",
    name = "Bright Linen Bandage",
    patchTag = "midnight-1",
    recipeID = 1228941,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 1,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Bandage",
        itemIDs = { 239711 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_crown__midnight_1",
    name = "Martyr's Crown",
    patchTag = "midnight-1",
    recipeID = 1228942,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Crown",
        itemIDs = { 239652 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_gloves__midnight_1",
    name = "Martyr's Gloves",
    patchTag = "midnight-1",
    recipeID = 1228943,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Gloves",
        itemIDs = { 239653 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_waistwrap__midnight_1",
    name = "Martyr's Waistwrap",
    patchTag = "midnight-1",
    recipeID = 1228944,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Waistwrap",
        itemIDs = { 239649 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_bindings__midnight_1",
    name = "Martyr's Bindings",
    patchTag = "midnight-1",
    recipeID = 1228945,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Bindings",
        itemIDs = { 239648 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_vestments__midnight_1",
    name = "Martyr's Vestments",
    patchTag = "midnight-1",
    recipeID = 1228946,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Vestments",
        itemIDs = { 239655 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_leggings__midnight_1",
    name = "Martyr's Leggings",
    patchTag = "midnight-1",
    recipeID = 1228947,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Leggings",
        itemIDs = { 239651 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_slippers__midnight_1",
    name = "Martyr's Slippers",
    patchTag = "midnight-1",
    recipeID = 1228948,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Slippers",
        itemIDs = { 239654 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__martyrs_mantle__midnight_1",
    name = "Martyr's Mantle",
    patchTag = "midnight-1",
    recipeID = 1228949,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 8,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Peerless Plumage",
        itemIDs = { 238522 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 12,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Martyr's Mantle",
        itemIDs = { 239650 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__adherents_silken_shroud__midnight_1",
    name = "Adherent's Silken Shroud",
    patchTag = "midnight-1",
    recipeID = 1228950,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 6,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 6,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Adherent's Silken Shroud",
        itemIDs = { 239656 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_helm__midnight_1",
    name = "Courtly Helm",
    patchTag = "midnight-1",
    recipeID = 1228951,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Helm",
        itemIDs = { 239668 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_gloves__midnight_1",
    name = "Courtly Gloves",
    patchTag = "midnight-1",
    recipeID = 1228952,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Gloves",
        itemIDs = { 239669 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_belt__midnight_1",
    name = "Courtly Belt",
    patchTag = "midnight-1",
    recipeID = 1228953,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Belt",
        itemIDs = { 239670 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_wrists__midnight_1",
    name = "Courtly Wrists",
    patchTag = "midnight-1",
    recipeID = 1228954,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Wrists",
        itemIDs = { 239671 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_robes__midnight_1",
    name = "Courtly Robes",
    patchTag = "midnight-1",
    recipeID = 1228955,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Robes",
        itemIDs = { 239672 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_pants__midnight_1",
    name = "Courtly Pants",
    patchTag = "midnight-1",
    recipeID = 1228956,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Pants",
        itemIDs = { 239676 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_slippers__midnight_1",
    name = "Courtly Slippers",
    patchTag = "midnight-1",
    recipeID = 1228957,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Slippers",
        itemIDs = { 239673 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_cloak__midnight_1",
    name = "Courtly Cloak",
    patchTag = "midnight-1",
    recipeID = 1228958,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Cloak",
        itemIDs = { 239674 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__courtly_shoulders__midnight_1",
    name = "Courtly Shoulders",
    patchTag = "midnight-1",
    recipeID = 1228959,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 1,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Courtly Shoulders",
        itemIDs = { 239675 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_silk_lining__midnight_1",
    name = "Sunfire Silk Lining",
    patchTag = "midnight-1",
    recipeID = 1228960,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 6,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Silk Lining",
        itemIDs = { 240164, 240165 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_lining__midnight_1",
    name = "Arcanoweave Lining",
    patchTag = "midnight-1",
    recipeID = 1228961,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 6,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Lining",
        itemIDs = { 240166, 240167 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_alchemy_coveralls__midnight_1",
    name = "Elegant Artisan's Alchemy Coveralls",
    patchTag = "midnight-1",
    recipeID = 1228962,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Alchemy Coveralls",
        itemIDs = { 239635 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_cooking_hat__midnight_1",
    name = "Elegant Artisan's Cooking Hat",
    patchTag = "midnight-1",
    recipeID = 1228963,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 5,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Cooking Hat",
        itemIDs = { 239636 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_enchanting_hat__midnight_1",
    name = "Elegant Artisan's Enchanting Hat",
    patchTag = "midnight-1",
    recipeID = 1228964,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Enchanting Hat",
        itemIDs = { 239637 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_fishing_hat__midnight_1",
    name = "Elegant Artisan's Fishing Hat",
    patchTag = "midnight-1",
    recipeID = 1228965,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 5,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Fishing Hat",
        itemIDs = { 239638 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_herbalism_hat__midnight_1",
    name = "Elegant Artisan's Herbalism Hat",
    patchTag = "midnight-1",
    recipeID = 1228966,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 5,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Herbalism Hat",
        itemIDs = { 239639 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__elegant_artisans_tailoring_robe__midnight_1",
    name = "Elegant Artisan's Tailoring Robe",
    patchTag = "midnight-1",
    recipeID = 1228967,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 5,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 3,
      },
    },
    outputs = {
      {
        itemRef = "Elegant Artisan's Tailoring Robe",
        itemIDs = { 239640 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_alchemy_apron__midnight_1",
    name = "Bright Linen Alchemy Apron",
    patchTag = "midnight-1",
    recipeID = 1228968,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 5,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Alchemy Apron",
        itemIDs = { 239641 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__chefs_bright_linen_cooking_chapeau__midnight_1",
    name = "Chef's Bright Linen Cooking Chapeau",
    patchTag = "midnight-1",
    recipeID = 1228969,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Chef's Bright Linen Cooking Chapeau",
        itemIDs = { 239642 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_enchanting_hat__midnight_1",
    name = "Bright Linen Enchanting Hat",
    patchTag = "midnight-1",
    recipeID = 1228970,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Enchanting Hat",
        itemIDs = { 239643 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_fishing_hat__midnight_1",
    name = "Bright Linen Fishing Hat",
    patchTag = "midnight-1",
    recipeID = 1228971,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Fishing Hat",
        itemIDs = { 239644 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_herbalism_hat__midnight_1",
    name = "Bright Linen Herbalism Hat",
    patchTag = "midnight-1",
    recipeID = 1228972,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Herbalism Hat",
        itemIDs = { 239645 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_tailoring_robe__midnight_1",
    name = "Bright Linen Tailoring Robe",
    patchTag = "midnight-1",
    recipeID = 1228973,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Tailoring Robe",
        itemIDs = { 239646 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_silk_spellthread__midnight_1",
    name = "Sunfire Silk Spellthread",
    patchTag = "midnight-1",
    recipeID = 1228974,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 6,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 12,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Silk Spellthread",
        itemIDs = { 240094 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_spellthread__midnight_1",
    name = "Arcanoweave Spellthread",
    patchTag = "midnight-1",
    recipeID = 1228975,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 6,
      },
      {
        itemRef = "Petrified Root",
        itemIDs = { 251285 },
        amount = 4,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 12,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Spellthread",
        itemIDs = { 240154 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_spellthread__midnight_1",
    name = "Bright Linen Spellthread",
    patchTag = "midnight-1",
    recipeID = 1228976,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 3,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 2,
      },
      {
        itemRef = "Eversinging Dust",
        itemIDs = { 243599 },
        amount = 2,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Spellthread",
        itemIDs = { 240156 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__imbued_bright_linen_backpack__midnight_1",
    name = "Imbued Bright Linen Backpack",
    patchTag = "midnight-1",
    recipeID = 1228977,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 8,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Imbued Bright Linen Backpack",
        itemIDs = { 240160 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__bright_linen_reagent_satchel__midnight_1",
    name = "Bright Linen Reagent Satchel",
    patchTag = "midnight-1",
    recipeID = 1228978,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 8,
      },
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Reagent Satchel",
        itemIDs = { 240159 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_reagent_rucksack__midnight_1",
    name = "Arcanoweave Reagent Rucksack",
    patchTag = "midnight-1",
    recipeID = 1228979,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 6,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 32,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Reagent Rucksack",
        itemIDs = { 240158 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_silk_backpack__midnight_1",
    name = "Sunfire Silk Backpack",
    patchTag = "midnight-1",
    recipeID = 1228980,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 2,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 6,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 32,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Silk Backpack",
        itemIDs = { 240161 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_bracers__midnight_1",
    name = "Sunfire Bracers",
    patchTag = "midnight-1",
    recipeID = 1228981,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 12,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 20,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 6,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Bracers",
        itemIDs = { 239657 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_cloak__midnight_1",
    name = "Sunfire Cloak",
    patchTag = "midnight-1",
    recipeID = 1228982,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 4,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Cloak",
        itemIDs = { 239658 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_treads__midnight_1",
    name = "Sunfire Treads",
    patchTag = "midnight-1",
    recipeID = 1228983,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 10,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Treads",
        itemIDs = { 239659 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_bracers__midnight_1",
    name = "Arcanoweave Bracers",
    patchTag = "midnight-1",
    recipeID = 1228984,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 20,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 6,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Bracers",
        itemIDs = { 239660 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_cloak__midnight_1",
    name = "Arcanoweave Cloak",
    patchTag = "midnight-1",
    recipeID = 1228985,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Fantastic Fur",
        itemIDs = { 238525 },
        amount = 4,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 10,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Cloak",
        itemIDs = { 239661 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_treads__midnight_1",
    name = "Arcanoweave Treads",
    patchTag = "midnight-1",
    recipeID = 1228986,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 10,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 10,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Treads",
        itemIDs = { 239662 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__sunfire_sash__midnight_1",
    name = "Sunfire Sash",
    patchTag = "midnight-1",
    recipeID = 1228987,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Sunfire Silk",
        itemIDs = { 237015, 237016 },
        amount = 15,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Sunfire Sash",
        itemIDs = { 239663 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__arcanoweave_cord__midnight_1",
    name = "Arcanoweave Cord",
    patchTag = "midnight-1",
    recipeID = 1228988,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Embroidery Floss",
        itemIDs = { 251691 },
        amount = 5,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 12,
      },
      {
        itemRef = "Tormented Tantalum",
        itemIDs = { 251283 },
        amount = 1,
      },
      {
        itemRef = "Arcanoweave",
        itemIDs = { 237017, 237018 },
        amount = 15,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Radiant Shard",
        itemIDs = { 243602, 243603 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Arcanoweave Cord",
        itemIDs = { 239664 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_bands__midnight_1",
    name = "Thalassian Competitor's Cloth Bands",
    patchTag = "midnight-1",
    recipeID = 1228989,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Bands",
        itemIDs = { 239677 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_cloak__midnight_1",
    name = "Thalassian Competitor's Cloth Cloak",
    patchTag = "midnight-1",
    recipeID = 1228990,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Cloak",
        itemIDs = { 239678 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_gloves__midnight_1",
    name = "Thalassian Competitor's Cloth Gloves",
    patchTag = "midnight-1",
    recipeID = 1228991,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Gloves",
        itemIDs = { 239679 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_hood__midnight_1",
    name = "Thalassian Competitor's Cloth Hood",
    patchTag = "midnight-1",
    recipeID = 1228992,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Hood",
        itemIDs = { 239680 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_leggings__midnight_1",
    name = "Thalassian Competitor's Cloth Leggings",
    patchTag = "midnight-1",
    recipeID = 1228993,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Wild Magic",
        itemIDs = { 236951 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Leggings",
        itemIDs = { 239681 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_sash__midnight_1",
    name = "Thalassian Competitor's Cloth Sash",
    patchTag = "midnight-1",
    recipeID = 1228994,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Sash",
        itemIDs = { 239682 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_shoulderpads__midnight_1",
    name = "Thalassian Competitor's Cloth Shoulderpads",
    patchTag = "midnight-1",
    recipeID = 1228995,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Primal Energy",
        itemIDs = { 236950 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Shoulderpads",
        itemIDs = { 239683 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_treads__midnight_1",
    name = "Thalassian Competitor's Cloth Treads",
    patchTag = "midnight-1",
    recipeID = 1228996,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Light",
        itemIDs = { 236949 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Treads",
        itemIDs = { 239684 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__thalassian_competitors_cloth_tunic__midnight_1",
    name = "Thalassian Competitor's Cloth Tunic",
    patchTag = "midnight-1",
    recipeID = 1228997,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 2,
      },
      {
        itemRef = "Mote of Pure Void",
        itemIDs = { 236952 },
        amount = 4,
      },
      {
        itemRef = "Carving Canine",
        itemIDs = { 238523 },
        amount = 4,
      },
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        amount = 6,
      },
    },
    outputs = {
      {
        itemRef = "Thalassian Competitor's Cloth Tunic",
        itemIDs = { 239685 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__silvermoon_curtains__midnight_1",
    name = "Silvermoon Curtains",
    patchTag = "midnight-1",
    recipeID = 1229000,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 24,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Silvermoon Curtains",
        itemIDs = { 262599 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__lush_telogrus_carpet__midnight_1",
    name = "Lush Telogrus Carpet",
    patchTag = "midnight-1",
    recipeID = 1229001,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 18,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Lush Telogrus Carpet",
        itemIDs = { 262352 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__luxurious_silvermoon_lounge_cushion__midnight_1",
    name = "Luxurious Silvermoon Lounge Cushion",
    patchTag = "midnight-1",
    recipeID = 1229002,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 12,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Luxurious Silvermoon Lounge Cushion",
        itemIDs = { 262591 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__plush_silvermoon_bed__midnight_1",
    name = "Plush Silvermoon Bed",
    patchTag = "midnight-1",
    recipeID = 1229003,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 46,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Plush Silvermoon Bed",
        itemIDs = { 262592 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__chic_silvermoon_pillow__midnight_1",
    name = "Chic Silvermoon Pillow",
    patchTag = "midnight-1",
    recipeID = 1246919,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 8,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Chic Silvermoon Pillow",
        itemIDs = { 262593 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__voidstrider_saddlebag__midnight_1",
    name = "Voidstrider Saddlebag",
    patchTag = "midnight-1",
    recipeID = 1246929,
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 3,
      },
      {
        itemRef = "Thalassian Lumber",
        itemIDs = { 256963 },
        amount = 16,
      },
      {
        itemRef = "Arcanoweave Bolt",
        itemIDs = { 239198, 239200 },
        amount = 8,
      },
      {
        itemRef = "Sunfire Silk Bolt",
        itemIDs = { 239201, 239202 },
        amount = 8,
      },
    },
    outputs = {
      {
        itemRef = "Voidstrider Saddlebag",
        itemIDs = { 262611 },
        baseAmount = 1,
      },
    },
  },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__thalassian_alchemy_coveralls__midnight_1",
--     name = "Thalassian Alchemy Coveralls",
--     patchTag = "midnight-1",
--     recipeID = 1279123,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Primal Energy",
--         itemIDs = { 236950 },
--         amount = 5,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 8,
--       },
--       {
--         itemRef = "Radiant Shard",
--         itemIDs = { 243602, 243603 },
--         amount = 3,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Thalassian Alchemy Coveralls",
--         itemIDs = { 267052 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__thalassian_chefs_chapeau__midnight_1",
--     name = "Thalassian Chef's Chapeau",
--     patchTag = "midnight-1",
--     recipeID = 1279124,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Light",
--         itemIDs = { 236949 },
--         amount = 5,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Sunfire Silk Bolt",
--         itemIDs = { 239201, 239202 },
--         amount = 8,
--       },
--       {
--         itemRef = "Radiant Shard",
--         itemIDs = { 243602, 243603 },
--         amount = 3,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Thalassian Chef's Chapeau",
--         itemIDs = { 267054 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__thalassian_enchanters_bonnet__midnight_1",
--     name = "Thalassian Enchanter's Bonnet",
--     patchTag = "midnight-1",
--     recipeID = 1279125,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Wild Magic",
--         itemIDs = { 236951 },
--         amount = 5,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 8,
--       },
--       {
--         itemRef = "Radiant Shard",
--         itemIDs = { 243602, 243603 },
--         amount = 3,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Thalassian Enchanter's Bonnet",
--         itemIDs = { 267056 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__thalassian_herbalists_cowl__midnight_1",
--     name = "Thalassian Herbalist's Cowl",
--     patchTag = "midnight-1",
--     recipeID = 1279128,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Wild Magic",
--         itemIDs = { 236951 },
--         amount = 5,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 8,
--       },
--       {
--         itemRef = "Radiant Shard",
--         itemIDs = { 243602, 243603 },
--         amount = 3,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Thalassian Herbalist's Cowl",
--         itemIDs = { 267060 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__thalassian_tailors_threads__midnight_1",
--     name = "Thalassian Tailor's Threads",
--     patchTag = "midnight-1",
--     recipeID = 1279129,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Pure Void",
--         itemIDs = { 236952 },
--         amount = 5,
--       },
--       {
--         itemRef = "Fused Vitality",
--         itemIDs = { 245345 },
--         amount = 20,
--       },
--       {
--         itemRef = "Sunfire Silk Bolt",
--         itemIDs = { 239201, 239202 },
--         amount = 8,
--       },
--       {
--         itemRef = "Radiant Shard",
--         itemIDs = { 243602, 243603 },
--         amount = 3,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Thalassian Tailor's Threads",
--         itemIDs = { 267062 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__smugglers_cloak__midnight_1",
--     name = "Smuggler's Cloak",
--     patchTag = "midnight-1",
--     recipeID = 1280541,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Pure Void",
--         itemIDs = { 236952 },
--         amount = 6,
--       },
--       {
--         itemRef = "Arcanoweave",
--         itemIDs = { 237017, 237018 },
--         amount = 10,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Smuggler's Cloak",
--         itemIDs = { 267444 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__silvermoon_agents_drape__midnight_1",
--     name = "Silvermoon Agent's Drape",
--     patchTag = "midnight-1",
--     recipeID = 1280542,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Light",
--         itemIDs = { 236949 },
--         amount = 6,
--       },
--       {
--         itemRef = "Sunfire Silk",
--         itemIDs = { 237015, 237016 },
--         amount = 10,
--       },
--       {
--         itemRef = "Sunfire Silk Bolt",
--         itemIDs = { 239201, 239202 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Silvermoon Agent's Drape",
--         itemIDs = { 267445 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__scouts_cape__midnight_1",
--     name = "Scout's Cape",
--     patchTag = "midnight-1",
--     recipeID = 1280543,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Light",
--         itemIDs = { 236949 },
--         amount = 6,
--       },
--       {
--         itemRef = "Arcanoweave",
--         itemIDs = { 237017, 237018 },
--         amount = 10,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Scout's Cape",
--         itemIDs = { 267446 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__farstriders_embroidered_cover__midnight_1",
--     name = "Farstrider's Embroidered Cover",
--     patchTag = "midnight-1",
--     recipeID = 1280544,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Primal Energy",
--         itemIDs = { 236950 },
--         amount = 6,
--       },
--       {
--         itemRef = "Sunfire Silk",
--         itemIDs = { 237015, 237016 },
--         amount = 10,
--       },
--       {
--         itemRef = "Sunfire Silk Bolt",
--         itemIDs = { 239201, 239202 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Farstrider's Embroidered Cover",
--         itemIDs = { 267447 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__blood_tempered_cape__midnight_1",
--     name = "Blood-Tempered Cape",
--     patchTag = "midnight-1",
--     recipeID = 1280545,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Wild Magic",
--         itemIDs = { 236951 },
--         amount = 6,
--       },
--       {
--         itemRef = "Arcanoweave",
--         itemIDs = { 237017, 237018 },
--         amount = 10,
--       },
--       {
--         itemRef = "Arcanoweave Bolt",
--         itemIDs = { 239198, 239200 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Blood-Tempered Cape",
--         itemIDs = { 267448 },
--         baseAmount = 1,
--       },
--     },
--   },
  -- DISABLED: Output is Bind on Pickup or Warbound on Wowhead; excluded from pricing.
--   {
--     id = "tailoring__spellbreakers_shroud__midnight_1",
--     name = "Spellbreaker's Shroud",
--     patchTag = "midnight-1",
--     recipeID = 1280546,
--     formulaProfile = "tailoring",
--     inputs = {
--       {
--         itemRef = "Embroidery Floss",
--         itemIDs = { 251691 },
--         amount = 2,
--       },
--       {
--         itemRef = "Mote of Pure Void",
--         itemIDs = { 236952 },
--         amount = 6,
--       },
--       {
--         itemRef = "Sunfire Silk",
--         itemIDs = { 237015, 237016 },
--         amount = 10,
--       },
--       {
--         itemRef = "Sunfire Silk Bolt",
--         itemIDs = { 239201, 239202 },
--         amount = 32,
--       },
--     },
--     outputs = {
--       {
--         itemRef = "Spellbreaker's Shroud",
--         itemIDs = { 267449 },
--         baseAmount = 1,
--       },
--     },
--   },
}
