-- GoldAdvisorMidnight/Data/Professions/Tailoring.lua
-- AUTO-GENERATED by tools/generate_profession_craft_data.py; do not edit manually.
-- Compact craft facts by profession: craft name, ranked input IDs/amounts, and base outputs.
GAM_PROFESSION_CRAFTS = GAM_PROFESSION_CRAFTS or {}

GAM_PROFESSION_CRAFTS["Tailoring"] = {
  {
    id = "tailoring__bright_linen_bolt__midnight_1",
    name = "Bright Linen Bolt",
    patchTag = "midnight-1",
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Bright Linen",
        itemIDs = { 236963, 236965 },
        amount = 1,
      },
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        baseAmount = 1,
      },
    },
  },
  {
    id = "tailoring__imbued_bright_linen_bolt__midnight_1",
    name = "Imbued Bright Linen Bolt",
    patchTag = "midnight-1",
    formulaProfile = "tailoring",
    inputs = {
      {
        itemRef = "Bright Linen Bolt",
        itemIDs = { 239700, 239701 },
        amount = 2,
      },
      {
        itemRef = "Silverleaf Thread",
        itemIDs = { 251665 },
        amount = 4,
      },
    },
    outputs = {
      {
        itemRef = "Imbued Bright Linen Bolt",
        itemIDs = { 239702, 239703 },
        baseAmount = 1,
      },
    },
  },
}
