#!/usr/bin/env python3
"""
encode_data.py — Gold Advisor Midnight data file encoder.

Encodes StratsGenerated.lua and WorkbookGenerated.lua into opaque blobs
that the in-addon decoder reconstructs at runtime using XOR + custom base64.

Usage:
    python tools/encode_data.py
    python tools/encode_data.py --key OverrideKey

The XOR key and base64 alphabet MUST match what the Lua decoder assembles
from the scattered fragments in the existing addon source files.

Lua fragment map (do not change without updating the addon source too):
    XOR key assembled from:
        GAM._vt  in Core.lua     → "Midnight"
        GAM._ls  in Log.lua      → "Gold"
        GAM._ms  in Minimap.lua  → "2026"
        Combined: GAM._vt .. GAM._ls .. GAM._ms  →  "MidnightGold2026"

    Base64 alphabet assembled from:
        GAM._ea  in Locale.lua   → first 32 chars
        GAM._eb  in Pricing.lua  → last 32 chars
        Combined: GAM._ea .. GAM._eb
"""

import base64
import argparse
import os
import re

# ── Encoding config ───────────────────────────────────────────────────────────
# Must match exactly what the Lua decoder assembles from addon source fragments.

XOR_KEY = "MidnightGold2026"

# Custom base64 alphabet — 64 unique chars, NOT standard order.
# Stored in addon as two 32-char halves in Locale.lua and Pricing.lua.
# Anyone naive-base64-decoding the data file will get garbage without this.
CUSTOM_B64 = (
    "QRSTUVWXYZabcdefvutsrqponmlkjihg"   # GAM._ea → goes in Locale.lua
    "wxyz0123456789+/ABCDEFGHIJKLMNOP"   # GAM._eb → goes in Pricing.lua
)

STANDARD_B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

assert len(CUSTOM_B64) == 64, "Custom alphabet must be exactly 64 chars"
assert len(set(CUSTOM_B64)) == 64, "Custom alphabet must have no duplicate chars"


# ── Encode helpers ────────────────────────────────────────────────────────────

def xor_bytes(data: bytes, key: str) -> bytes:
    key_bytes = key.encode("utf-8")
    key_len = len(key_bytes)
    return bytes(b ^ key_bytes[i % key_len] for i, b in enumerate(data))


def custom_b64_encode(data: bytes) -> str:
    """Base64-encode using CUSTOM_B64 alphabet instead of the standard one."""
    standard = base64.b64encode(data).decode("ascii")
    trans = str.maketrans(STANDARD_B64, CUSTOM_B64)
    return standard.translate(trans)


def encode_file(src_path: str, dst_path: str, global_name: str, key: str) -> None:
    # Read as binary to preserve exact bytes (including CRLF line endings)
    with open(src_path, "rb") as f:
        original_bytes = f.read()

    xored   = xor_bytes(original_bytes, key)
    encoded = custom_b64_encode(xored)

    output = (
        f"-- Encoded data file. Do not edit manually.\n"
        f"-- Generated by tools/encode_data.py\n"
        f"{global_name} = \"{encoded}\"\n"
    )

    with open(dst_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(output)

    print(f"  {os.path.basename(src_path):30s} → {os.path.basename(dst_path)}")
    print(f"    Original size : {len(original_bytes):>10,} bytes")
    print(f"    Encoded size  : {len(encoded):>10,} chars")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Encode GAM data files.")
    parser.add_argument("--key", default=XOR_KEY, help="Override XOR key")
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "..", "source", "GoldAdvisorMidnight", "Data")

    files = [
        ("StratsGenerated.lua",   "StratsEncoded.lua",   "GAM_STRATS_ENCODED"),
        ("WorkbookGenerated.lua", "WorkbookEncoded.lua", "GAM_WORKBOOK_ENCODED"),
    ]

    print(f"Encoding with key: {'*' * len(args.key)}  (custom alphabet active)\n")

    for src_name, dst_name, global_name in files:
        src = os.path.join(data_dir, src_name)
        dst = os.path.join(data_dir, dst_name)
        if not os.path.exists(src):
            print(f"  SKIP: {src_name} not found")
            continue
        encode_file(src, dst, global_name, args.key)
        print()

    print("Done.")


if __name__ == "__main__":
    main()
